/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { AchievementsResponse } from "../models/index";
import {
  AchievementsResponseFromJSON,
  AchievementsResponseToJSON,
} from "../models/index";

export interface AchievementsControllerFindAllbyUserIdRequest {
  userId: number;
}

/**
 *
 */
export class AchievementsApi extends runtime.BaseAPI {
  /**
   * Get all achievements for a user
   */
  async achievementsControllerFindAllbyUserIdRaw(
    requestParameters: AchievementsControllerFindAllbyUserIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AchievementsResponse>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling achievementsControllerFindAllbyUserId().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["userId"] != null) {
      queryParameters["userId"] = requestParameters["userId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/achievements`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AchievementsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get all achievements for a user
   */
  async achievementsControllerFindAllbyUserId(
    requestParameters: AchievementsControllerFindAllbyUserIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AchievementsResponse> {
    const response = await this.achievementsControllerFindAllbyUserIdRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
