/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAchievementDto,
  UpdateAchievementDto,
} from '../models/index';
import {
    CreateAchievementDtoFromJSON,
    CreateAchievementDtoToJSON,
    UpdateAchievementDtoFromJSON,
    UpdateAchievementDtoToJSON,
} from '../models/index';

export interface AchievementsCreateRequest {
    createAchievementDto: CreateAchievementDto;
}

export interface AchievementsFindOneRequest {
    id: number;
}

export interface AchievementsRemoveRequest {
    id: number;
}

export interface AchievementsUpdateRequest {
    id: number;
    updateAchievementDto: UpdateAchievementDto;
}

/**
 * 
 */
export class AchievementsApi extends runtime.BaseAPI {

    /**
     * Create an achievement
     */
    async achievementsCreateRaw(requestParameters: AchievementsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createAchievementDto'] == null) {
            throw new runtime.RequiredError(
                'createAchievementDto',
                'Required parameter "createAchievementDto" was null or undefined when calling achievementsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/achievements`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAchievementDtoToJSON(requestParameters['createAchievementDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create an achievement
     */
    async achievementsCreate(requestParameters: AchievementsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.achievementsCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all achievements
     */
    async achievementsFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievements`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve all achievements
     */
    async achievementsFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.achievementsFindAllRaw(initOverrides);
    }

    /**
     * Retrieve a specific achievement by ID
     */
    async achievementsFindOneRaw(requestParameters: AchievementsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling achievementsFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievements/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve a specific achievement by ID
     */
    async achievementsFindOne(requestParameters: AchievementsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.achievementsFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a specific achievement by ID
     */
    async achievementsRemoveRaw(requestParameters: AchievementsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling achievementsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievements/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specific achievement by ID
     */
    async achievementsRemove(requestParameters: AchievementsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.achievementsRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Update a specific achievement by ID
     */
    async achievementsUpdateRaw(requestParameters: AchievementsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling achievementsUpdate().'
            );
        }

        if (requestParameters['updateAchievementDto'] == null) {
            throw new runtime.RequiredError(
                'updateAchievementDto',
                'Required parameter "updateAchievementDto" was null or undefined when calling achievementsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/achievements/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAchievementDtoToJSON(requestParameters['updateAchievementDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a specific achievement by ID
     */
    async achievementsUpdate(requestParameters: AchievementsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.achievementsUpdateRaw(requestParameters, initOverrides);
    }

}
