/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * 42 OAuth callback
     */
    async authFortyTwoCallbackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/42/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 42 OAuth callback
     */
    async authFortyTwoCallback(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authFortyTwoCallbackRaw(initOverrides);
    }

    /**
     * Login with 42 OAuth
     */
    async authFortyTwoLoginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/42/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Login with 42 OAuth
     */
    async authFortyTwoLogin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authFortyTwoLoginRaw(initOverrides);
    }

    /**
     * Logout from 42 OAuth
     */
    async authFortyTwoLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/42/logout`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout from 42 OAuth
     */
    async authFortyTwoLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authFortyTwoLogoutRaw(initOverrides);
    }

}
