/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { DevLoginResponseDto } from "../models/index";
import {
  DevLoginResponseDtoFromJSON,
  DevLoginResponseDtoToJSON,
} from "../models/index";

export interface AuthControllerDevLoginRequest {
  userId: number;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Login with to any account by id
   */
  async authControllerDevLoginRaw(
    requestParameters: AuthControllerDevLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DevLoginResponseDto>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling authControllerDevLogin().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/auth/dev/login/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DevLoginResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Login with to any account by id
   */
  async authControllerDevLogin(
    requestParameters: AuthControllerDevLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DevLoginResponseDto> {
    const response = await this.authControllerDevLoginRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * 42 OAuth callback
   */
  async authControllerFortyTwoCallbackRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/auth/42/callback`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 42 OAuth callback
   */
  async authControllerFortyTwoCallback(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.authControllerFortyTwoCallbackRaw(initOverrides);
  }

  /**
   * Login with 42 OAuth
   */
  async authControllerFortyTwoLoginRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/auth/42/login`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Login with 42 OAuth
   */
  async authControllerFortyTwoLogin(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.authControllerFortyTwoLoginRaw(initOverrides);
  }

  /**
   * Logout user
   */
  async authControllerLogoutRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/auth/logout`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Logout user
   */
  async authControllerLogout(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.authControllerLogoutRaw(initOverrides);
  }
}
