/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateBlockedDto,
} from '../models/index';
import {
    CreateBlockedDtoFromJSON,
    CreateBlockedDtoToJSON,
} from '../models/index';

export interface BlockedsCreateRequest {
    createBlockedDto: CreateBlockedDto;
}

export interface BlockedsFindOneRequest {
    id: string;
}

export interface BlockedsRemoveRequest {
    id: string;
}

/**
 * 
 */
export class BlockedsApi extends runtime.BaseAPI {

    /**
     * Create a blocked entry
     */
    async blockedsCreateRaw(requestParameters: BlockedsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createBlockedDto'] == null) {
            throw new runtime.RequiredError(
                'createBlockedDto',
                'Required parameter "createBlockedDto" was null or undefined when calling blockedsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blockeds`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBlockedDtoToJSON(requestParameters['createBlockedDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a blocked entry
     */
    async blockedsCreate(requestParameters: BlockedsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blockedsCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all blocked entries
     */
    async blockedsFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blockeds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve all blocked entries
     */
    async blockedsFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blockedsFindAllRaw(initOverrides);
    }

    /**
     * Retrieve a blocked entry by user ID
     */
    async blockedsFindOneRaw(requestParameters: BlockedsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blockedsFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blockeds/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve a blocked entry by user ID
     */
    async blockedsFindOne(requestParameters: BlockedsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blockedsFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a blocked entry by ID
     */
    async blockedsRemoveRaw(requestParameters: BlockedsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blockedsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blockeds/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a blocked entry by ID
     */
    async blockedsRemove(requestParameters: BlockedsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blockedsRemoveRaw(requestParameters, initOverrides);
    }

}
