/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ChatRoomResponse,
  ChatRoomsResponse,
  CreateChatRoomDto,
} from "../models/index";
import {
  ChatRoomResponseFromJSON,
  ChatRoomResponseToJSON,
  ChatRoomsResponseFromJSON,
  ChatRoomsResponseToJSON,
  CreateChatRoomDtoFromJSON,
  CreateChatRoomDtoToJSON,
} from "../models/index";

export interface ChatRoomsControllerCreateRequest {
  createChatRoomDto: CreateChatRoomDto;
}

export interface ChatRoomsControllerFindOneRequest {
  id: number;
}

export interface ChatRoomsControllerRemoveRequest {
  id: number;
}

export interface ChatRoomsControllerUpdateRequest {
  id: number;
  body: object;
}

/**
 *
 */
export class ChatRoomsApi extends runtime.BaseAPI {
  /**
   * Create a new chat room and add the creator as an owner
   */
  async chatRoomsControllerCreateRaw(
    requestParameters: ChatRoomsControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChatRoomResponse>> {
    if (requestParameters["createChatRoomDto"] == null) {
      throw new runtime.RequiredError(
        "createChatRoomDto",
        'Required parameter "createChatRoomDto" was null or undefined when calling chatRoomsControllerCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/chatroom`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateChatRoomDtoToJSON(requestParameters["createChatRoomDto"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChatRoomResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create a new chat room and add the creator as an owner
   */
  async chatRoomsControllerCreate(
    requestParameters: ChatRoomsControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChatRoomResponse> {
    const response = await this.chatRoomsControllerCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of all chat rooms
   */
  async chatRoomsControllerFindAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/chatroom`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Get a list of all chat rooms
   */
  async chatRoomsControllerFindAll(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.chatRoomsControllerFindAllRaw(initOverrides);
  }

  /**
   * Get all public chat rooms
   */
  async chatRoomsControllerFindAllWithoutPrivateRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/chatroom/noPrivate`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Get all public chat rooms
   */
  async chatRoomsControllerFindAllWithoutPrivate(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.chatRoomsControllerFindAllWithoutPrivateRaw(initOverrides);
  }

  /**
   * Get all chat rooms including participants
   */
  async chatRoomsControllerFindAllincludeParticipantRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChatRoomsResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/chatroom/includeParticipant`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChatRoomsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get all chat rooms including participants
   */
  async chatRoomsControllerFindAllincludeParticipant(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChatRoomsResponse> {
    const response =
      await this.chatRoomsControllerFindAllincludeParticipantRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get a specific chat room by ID
   */
  async chatRoomsControllerFindOneRaw(
    requestParameters: ChatRoomsControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChatRoomResponse>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling chatRoomsControllerFindOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/chatroom/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChatRoomResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get a specific chat room by ID
   */
  async chatRoomsControllerFindOne(
    requestParameters: ChatRoomsControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChatRoomResponse> {
    const response = await this.chatRoomsControllerFindOneRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get all chat rooms the user can see
   */
  async chatRoomsControllerFindOverviewRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/chatroom/overview`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Get all chat rooms the user can see
   */
  async chatRoomsControllerFindOverview(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.chatRoomsControllerFindOverviewRaw(initOverrides);
  }

  /**
   * Delete a chat room by ID
   */
  async chatRoomsControllerRemoveRaw(
    requestParameters: ChatRoomsControllerRemoveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling chatRoomsControllerRemove().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/chatroom/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a chat room by ID
   */
  async chatRoomsControllerRemove(
    requestParameters: ChatRoomsControllerRemoveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.chatRoomsControllerRemoveRaw(requestParameters, initOverrides);
  }

  /**
   * Update a chat room by ID
   */
  async chatRoomsControllerUpdateRaw(
    requestParameters: ChatRoomsControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling chatRoomsControllerUpdate().',
      );
    }

    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling chatRoomsControllerUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/chatroom/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Update a chat room by ID
   */
  async chatRoomsControllerUpdate(
    requestParameters: ChatRoomsControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.chatRoomsControllerUpdateRaw(requestParameters, initOverrides);
  }
}
