/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateChatMessageDto,
} from '../models/index';
import {
    CreateChatMessageDtoFromJSON,
    CreateChatMessageDtoToJSON,
} from '../models/index';

export interface ChatMessagesCreateRequest {
    createChatMessageDto: CreateChatMessageDto;
}

export interface ChatMessagesFindAllByUserAndChatRoomRequest {
    chatRoomId: string;
    userId: string;
}

export interface ChatMessagesFindAllByUserIdRequest {
    userId: string;
}

export interface ChatMessagesFindOneRequest {
    id: string;
}

export interface ChatMessagesRemoveRequest {
    chatRoomId: string;
}

/**
 * 
 */
export class ChatMessagesApi extends runtime.BaseAPI {

    /**
     * Create a chat message
     */
    async chatMessagesCreateRaw(requestParameters: ChatMessagesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createChatMessageDto'] == null) {
            throw new runtime.RequiredError(
                'createChatMessageDto',
                'Required parameter "createChatMessageDto" was null or undefined when calling chatMessagesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chatMessages`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChatMessageDtoToJSON(requestParameters['createChatMessageDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a chat message
     */
    async chatMessagesCreate(requestParameters: ChatMessagesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatMessagesCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all chat messages
     */
    async chatMessagesFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatMessages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve all chat messages
     */
    async chatMessagesFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatMessagesFindAllRaw(initOverrides);
    }

    /**
     * Retrieve messages by user ID and chat room ID
     */
    async chatMessagesFindAllByUserAndChatRoomRaw(requestParameters: ChatMessagesFindAllByUserAndChatRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatMessagesFindAllByUserAndChatRoom().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling chatMessagesFindAllByUserAndChatRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatMessages/chatRoom/{chatRoomId}/user/{userId}`.replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve messages by user ID and chat room ID
     */
    async chatMessagesFindAllByUserAndChatRoom(requestParameters: ChatMessagesFindAllByUserAndChatRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatMessagesFindAllByUserAndChatRoomRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all messages by user ID
     */
    async chatMessagesFindAllByUserIdRaw(requestParameters: ChatMessagesFindAllByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling chatMessagesFindAllByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatMessages/user/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve all messages by user ID
     */
    async chatMessagesFindAllByUserId(requestParameters: ChatMessagesFindAllByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatMessagesFindAllByUserIdRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve chat messages by chat room ID
     */
    async chatMessagesFindOneRaw(requestParameters: ChatMessagesFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatMessagesFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatMessages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve chat messages by chat room ID
     */
    async chatMessagesFindOne(requestParameters: ChatMessagesFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatMessagesFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all chat messages for a chat room
     */
    async chatMessagesRemoveRaw(requestParameters: ChatMessagesRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatMessagesRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatMessages/{chatRoomId}`.replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete all chat messages for a chat room
     */
    async chatMessagesRemove(requestParameters: ChatMessagesRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatMessagesRemoveRaw(requestParameters, initOverrides);
    }

}
