/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateChatParticipantDto,
  UpdateChatParticipantDto,
} from '../models/index';
import {
    CreateChatParticipantDtoFromJSON,
    CreateChatParticipantDtoToJSON,
    UpdateChatParticipantDtoFromJSON,
    UpdateChatParticipantDtoToJSON,
} from '../models/index';

export interface ChatParticipantsAddParticipantToChatroomRequest {
    chatRoomId: number;
    userId: number;
}

export interface ChatParticipantsCreateRequest {
    createChatParticipantDto: CreateChatParticipantDto;
}

export interface ChatParticipantsFindOneRequest {
    id: string;
}

export interface ChatParticipantsFindParticipantByChatRoomRequest {
    chatRoomId: number;
}

export interface ChatParticipantsFindParticipantChatRoomUserIdRequest {
    chatRoomId: number;
    userId: number;
}

export interface ChatParticipantsRemoveRequest {
    id: string;
    chatRoomId: string;
}

export interface ChatParticipantsUpdateParticipantRequest {
    chatRoomId: number;
    id: number;
    updateChatParticipantDto: UpdateChatParticipantDto;
}

/**
 * 
 */
export class ChatParticipantsApi extends runtime.BaseAPI {

    /**
     * Add a participant to a chat room
     */
    async chatParticipantsAddParticipantToChatroomRaw(requestParameters: ChatParticipantsAddParticipantToChatroomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatParticipantsAddParticipantToChatroom().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling chatParticipantsAddParticipantToChatroom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatParticipants/{chatRoomId}/join/{userId}`.replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a participant to a chat room
     */
    async chatParticipantsAddParticipantToChatroom(requestParameters: ChatParticipantsAddParticipantToChatroomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsAddParticipantToChatroomRaw(requestParameters, initOverrides);
    }

    /**
     * Create a chat participant
     */
    async chatParticipantsCreateRaw(requestParameters: ChatParticipantsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createChatParticipantDto'] == null) {
            throw new runtime.RequiredError(
                'createChatParticipantDto',
                'Required parameter "createChatParticipantDto" was null or undefined when calling chatParticipantsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chatParticipants`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChatParticipantDtoToJSON(requestParameters['createChatParticipantDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a chat participant
     */
    async chatParticipantsCreate(requestParameters: ChatParticipantsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch all chat participants
     */
    async chatParticipantsFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatParticipants`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch all chat participants
     */
    async chatParticipantsFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsFindAllRaw(initOverrides);
    }

    /**
     * Fetch a chat participant by ID
     */
    async chatParticipantsFindOneRaw(requestParameters: ChatParticipantsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatParticipantsFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatParticipants/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch a chat participant by ID
     */
    async chatParticipantsFindOne(requestParameters: ChatParticipantsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch participants by chat room ID
     */
    async chatParticipantsFindParticipantByChatRoomRaw(requestParameters: ChatParticipantsFindParticipantByChatRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatParticipantsFindParticipantByChatRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatParticipants/{chatRoomId}/find`.replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch participants by chat room ID
     */
    async chatParticipantsFindParticipantByChatRoom(requestParameters: ChatParticipantsFindParticipantByChatRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsFindParticipantByChatRoomRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch participant in chat room by user ID
     */
    async chatParticipantsFindParticipantChatRoomUserIdRaw(requestParameters: ChatParticipantsFindParticipantChatRoomUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatParticipantsFindParticipantChatRoomUserId().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling chatParticipantsFindParticipantChatRoomUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatParticipants/{chatRoomId}/find/{userId}`.replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch participant in chat room by user ID
     */
    async chatParticipantsFindParticipantChatRoomUserId(requestParameters: ChatParticipantsFindParticipantChatRoomUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsFindParticipantChatRoomUserIdRaw(requestParameters, initOverrides);
    }

    /**
     * Remove a chat participant
     */
    async chatParticipantsRemoveRaw(requestParameters: ChatParticipantsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatParticipantsRemove().'
            );
        }

        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatParticipantsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatParticipants/{chatRoomId}/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a chat participant
     */
    async chatParticipantsRemove(requestParameters: ChatParticipantsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Update a chat participant
     */
    async chatParticipantsUpdateParticipantRaw(requestParameters: ChatParticipantsUpdateParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRoomId'] == null) {
            throw new runtime.RequiredError(
                'chatRoomId',
                'Required parameter "chatRoomId" was null or undefined when calling chatParticipantsUpdateParticipant().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatParticipantsUpdateParticipant().'
            );
        }

        if (requestParameters['updateChatParticipantDto'] == null) {
            throw new runtime.RequiredError(
                'updateChatParticipantDto',
                'Required parameter "updateChatParticipantDto" was null or undefined when calling chatParticipantsUpdateParticipant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chatParticipants/{chatRoomId}/update/{id}`.replace(`{${"chatRoomId"}}`, encodeURIComponent(String(requestParameters['chatRoomId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateChatParticipantDtoToJSON(requestParameters['updateChatParticipantDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a chat participant
     */
    async chatParticipantsUpdateParticipant(requestParameters: ChatParticipantsUpdateParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatParticipantsUpdateParticipantRaw(requestParameters, initOverrides);
    }

}
