/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateChatRoomDto,
} from '../models/index';
import {
    CreateChatRoomDtoFromJSON,
    CreateChatRoomDtoToJSON,
} from '../models/index';

export interface ChatRoomsCreateRequest {
    createChatRoomDto: CreateChatRoomDto;
}

export interface ChatRoomsFindOneRequest {
    id: string;
}

export interface ChatRoomsRemoveRequest {
    id: string;
}

export interface ChatRoomsUpdateRequest {
    id: string;
    body: object;
}

/**
 * 
 */
export class ChatRoomsApi extends runtime.BaseAPI {

    /**
     * Create a new chat room
     */
    async chatRoomsCreateRaw(requestParameters: ChatRoomsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createChatRoomDto'] == null) {
            throw new runtime.RequiredError(
                'createChatRoomDto',
                'Required parameter "createChatRoomDto" was null or undefined when calling chatRoomsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chatroom`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChatRoomDtoToJSON(requestParameters['createChatRoomDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new chat room
     */
    async chatRoomsCreate(requestParameters: ChatRoomsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Get a list of all chat rooms
     */
    async chatRoomsFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatroom`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a list of all chat rooms
     */
    async chatRoomsFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsFindAllRaw(initOverrides);
    }

    /**
     * Get all public chat rooms
     */
    async chatRoomsFindAllWithoutPrivateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatroom/noPrivate`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all public chat rooms
     */
    async chatRoomsFindAllWithoutPrivate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsFindAllWithoutPrivateRaw(initOverrides);
    }

    /**
     * Get all chat rooms including participants
     */
    async chatRoomsFindAllincludeParticipantRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatroom/includeParticipant`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all chat rooms including participants
     */
    async chatRoomsFindAllincludeParticipant(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsFindAllincludeParticipantRaw(initOverrides);
    }

    /**
     * Get a specific chat room by ID
     */
    async chatRoomsFindOneRaw(requestParameters: ChatRoomsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatRoomsFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatroom/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a specific chat room by ID
     */
    async chatRoomsFindOne(requestParameters: ChatRoomsFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a chat room by ID
     */
    async chatRoomsRemoveRaw(requestParameters: ChatRoomsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatRoomsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chatroom/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a chat room by ID
     */
    async chatRoomsRemove(requestParameters: ChatRoomsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Update a chat room by ID
     */
    async chatRoomsUpdateRaw(requestParameters: ChatRoomsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling chatRoomsUpdate().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling chatRoomsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chatroom/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a chat room by ID
     */
    async chatRoomsUpdate(requestParameters: ChatRoomsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatRoomsUpdateRaw(requestParameters, initOverrides);
    }

}
