/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FileUploadResponseSuccess,
} from '../models/index';
import {
    FileUploadResponseSuccessFromJSON,
    FileUploadResponseSuccessToJSON,
} from '../models/index';

export interface FileUploadControllerUploadFileRequest {
    file: Blob;
    filename?: string;
    category?: string;
}

/**
 * 
 */
export class FileUploadApi extends runtime.BaseAPI {

    /**
     */
    async fileUploadControllerUploadFileRaw(requestParameters: FileUploadControllerUploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileUploadResponseSuccess>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling fileUploadControllerUploadFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['filename'] != null) {
            formParams.append('filename', requestParameters['filename'] as any);
        }

        if (requestParameters['category'] != null) {
            formParams.append('category', requestParameters['category'] as any);
        }

        const response = await this.request({
            path: `/file-upload/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileUploadResponseSuccessFromJSON(jsonValue));
    }

    /**
     */
    async fileUploadControllerUploadFile(requestParameters: FileUploadControllerUploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileUploadResponseSuccess> {
        const response = await this.fileUploadControllerUploadFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
