/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { GetFriendRequestsDto } from "../models/index";
import {
  GetFriendRequestsDtoFromJSON,
  GetFriendRequestsDtoToJSON,
} from "../models/index";

export interface FriendsControllerSendFriendRequestRequest {
  id: number;
}

/**
 *
 */
export class FriendsApi extends runtime.BaseAPI {
  /**
   * Get all open requests for current user
   */
  async friendsControllerGetFriendRequestsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFriendRequestsDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends/requests`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetFriendRequestsDtoFromJSON(jsonValue),
    );
  }

  /**
   * Get all open requests for current user
   */
  async friendsControllerGetFriendRequests(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFriendRequestsDto> {
    const response =
      await this.friendsControllerGetFriendRequestsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get all friends for current user
   */
  async friendsControllerGetFriendsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFriendRequestsDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetFriendRequestsDtoFromJSON(jsonValue),
    );
  }

  /**
   * Get all friends for current user
   */
  async friendsControllerGetFriends(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFriendRequestsDto> {
    const response = await this.friendsControllerGetFriendsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Send a friend request by Id
   */
  async friendsControllerSendFriendRequestRaw(
    requestParameters: FriendsControllerSendFriendRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling friendsControllerSendFriendRequest().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends/requests/send/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Send a friend request by Id
   */
  async friendsControllerSendFriendRequest(
    requestParameters: FriendsControllerSendFriendRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.friendsControllerSendFriendRequestRaw(
      requestParameters,
      initOverrides,
    );
  }
}
