/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  FriendsControllerGetFriendStatus200Response,
  GetFriendRequestsDto,
} from "../models/index";
import {
  FriendsControllerGetFriendStatus200ResponseFromJSON,
  FriendsControllerGetFriendStatus200ResponseToJSON,
  GetFriendRequestsDtoFromJSON,
  GetFriendRequestsDtoToJSON,
} from "../models/index";

export interface FriendsControllerAcceptFriendRequestRequest {
  id: number;
}

export interface FriendsControllerGetFriendStatusRequest {
  id: number;
}

export interface FriendsControllerSendFriendRequestRequest {
  id: number;
}

/**
 *
 */
export class FriendsApi extends runtime.BaseAPI {
  /**
   * Accept a friend request by Id
   */
  async friendsControllerAcceptFriendRequestRaw(
    requestParameters: FriendsControllerAcceptFriendRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling friendsControllerAcceptFriendRequest().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends/requests/accept/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Accept a friend request by Id
   */
  async friendsControllerAcceptFriendRequest(
    requestParameters: FriendsControllerAcceptFriendRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.friendsControllerAcceptFriendRequestRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Get all open requests for current user
   */
  async friendsControllerGetFriendRequestsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFriendRequestsDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends/requests`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetFriendRequestsDtoFromJSON(jsonValue),
    );
  }

  /**
   * Get all open requests for current user
   */
  async friendsControllerGetFriendRequests(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFriendRequestsDto> {
    const response =
      await this.friendsControllerGetFriendRequestsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get friendship status with a user
   */
  async friendsControllerGetFriendStatusRaw(
    requestParameters: FriendsControllerGetFriendStatusRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FriendsControllerGetFriendStatus200Response>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling friendsControllerGetFriendStatus().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends/friend-status/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FriendsControllerGetFriendStatus200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get friendship status with a user
   */
  async friendsControllerGetFriendStatus(
    requestParameters: FriendsControllerGetFriendStatusRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FriendsControllerGetFriendStatus200Response> {
    const response = await this.friendsControllerGetFriendStatusRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get all friends for current user
   */
  async friendsControllerGetFriendsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFriendRequestsDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetFriendRequestsDtoFromJSON(jsonValue),
    );
  }

  /**
   * Get all friends for current user
   */
  async friendsControllerGetFriends(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFriendRequestsDto> {
    const response = await this.friendsControllerGetFriendsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Send a friend request by Id
   */
  async friendsControllerSendFriendRequestRaw(
    requestParameters: FriendsControllerSendFriendRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling friendsControllerSendFriendRequest().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/friends/requests/send/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Send a friend request by Id
   */
  async friendsControllerSendFriendRequest(
    requestParameters: FriendsControllerSendFriendRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.friendsControllerSendFriendRequestRaw(
      requestParameters,
      initOverrides,
    );
  }
}
