/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGameDto,
} from '../models/index';
import {
    CreateGameDtoFromJSON,
    CreateGameDtoToJSON,
} from '../models/index';

export interface GamesCreateRequest {
    createGameDto: CreateGameDto;
}

export interface GamesFindOneRequest {
    id: string;
}

export interface GamesRemoveRequest {
    id: string;
}

/**
 * 
 */
export class GamesApi extends runtime.BaseAPI {

    /**
     * Create a new game
     */
    async gamesCreateRaw(requestParameters: GamesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createGameDto'] == null) {
            throw new runtime.RequiredError(
                'createGameDto',
                'Required parameter "createGameDto" was null or undefined when calling gamesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/games`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGameDtoToJSON(requestParameters['createGameDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new game
     */
    async gamesCreate(requestParameters: GamesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gamesCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all games
     */
    async gamesFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve all games
     */
    async gamesFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gamesFindAllRaw(initOverrides);
    }

    /**
     * Retrieve a game by ID
     */
    async gamesFindOneRaw(requestParameters: GamesFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamesFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve a game by ID
     */
    async gamesFindOne(requestParameters: GamesFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gamesFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a game by ID
     */
    async gamesRemoveRaw(requestParameters: GamesRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamesRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a game by ID
     */
    async gamesRemove(requestParameters: GamesRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gamesRemoveRaw(requestParameters, initOverrides);
    }

}
