/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  AcceptInviteResponse,
  CreateInviteDto,
  Invite,
  InviteResponseDto,
} from "../models/index";
import {
  AcceptInviteResponseFromJSON,
  AcceptInviteResponseToJSON,
  CreateInviteDtoFromJSON,
  CreateInviteDtoToJSON,
  InviteFromJSON,
  InviteToJSON,
  InviteResponseDtoFromJSON,
  InviteResponseDtoToJSON,
} from "../models/index";

export interface InviteControllerAcceptInviteRequest {
  inviteId: number;
}

export interface InviteControllerCreateInviteRequest {
  createInviteDto: CreateInviteDto;
}

export interface InviteControllerDeclineInviteRequest {
  inviteId: number;
}

/**
 *
 */
export class InviteApi extends runtime.BaseAPI {
  /**
   * Accept a game invite
   */
  async inviteControllerAcceptInviteRaw(
    requestParameters: InviteControllerAcceptInviteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AcceptInviteResponse>> {
    if (requestParameters["inviteId"] == null) {
      throw new runtime.RequiredError(
        "inviteId",
        'Required parameter "inviteId" was null or undefined when calling inviteControllerAcceptInvite().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/invite/accept/{inviteId}`.replace(
          `{${"inviteId"}}`,
          encodeURIComponent(String(requestParameters["inviteId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AcceptInviteResponseFromJSON(jsonValue),
    );
  }

  /**
   * Accept a game invite
   */
  async inviteControllerAcceptInvite(
    requestParameters: InviteControllerAcceptInviteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AcceptInviteResponse> {
    const response = await this.inviteControllerAcceptInviteRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Send a game invite to another user
   */
  async inviteControllerCreateInviteRaw(
    requestParameters: InviteControllerCreateInviteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<InviteResponseDto>> {
    if (requestParameters["createInviteDto"] == null) {
      throw new runtime.RequiredError(
        "createInviteDto",
        'Required parameter "createInviteDto" was null or undefined when calling inviteControllerCreateInvite().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/invite/send`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateInviteDtoToJSON(requestParameters["createInviteDto"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      InviteResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Send a game invite to another user
   */
  async inviteControllerCreateInvite(
    requestParameters: InviteControllerCreateInviteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<InviteResponseDto> {
    const response = await this.inviteControllerCreateInviteRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Decline a game invite
   */
  async inviteControllerDeclineInviteRaw(
    requestParameters: InviteControllerDeclineInviteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<InviteResponseDto>> {
    if (requestParameters["inviteId"] == null) {
      throw new runtime.RequiredError(
        "inviteId",
        'Required parameter "inviteId" was null or undefined when calling inviteControllerDeclineInvite().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/invite/decline/{inviteId}`.replace(
          `{${"inviteId"}}`,
          encodeURIComponent(String(requestParameters["inviteId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      InviteResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Decline a game invite
   */
  async inviteControllerDeclineInvite(
    requestParameters: InviteControllerDeclineInviteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<InviteResponseDto> {
    const response = await this.inviteControllerDeclineInviteRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get all pending invites for a user
   */
  async inviteControllerGetPendingInvitesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Invite>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/invite/pending`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(InviteFromJSON),
    );
  }

  /**
   * Get all pending invites for a user
   */
  async inviteControllerGetPendingInvites(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Invite>> {
    const response =
      await this.inviteControllerGetPendingInvitesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get all sent invites for a user
   */
  async inviteControllerGetSentInvitesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Invite>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/invite/sent`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(InviteFromJSON),
    );
  }

  /**
   * Get all sent invites for a user
   */
  async inviteControllerGetSentInvites(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Invite>> {
    const response =
      await this.inviteControllerGetSentInvitesRaw(initOverrides);
    return await response.value();
  }
}
