/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { PlayerStatisticsDto } from "../models/index";
import {
  PlayerStatisticsDtoFromJSON,
  PlayerStatisticsDtoToJSON,
} from "../models/index";

export interface StatisticsControllerGetPlayerStatisticsByIdRequest {
  id: number;
}

/**
 *
 */
export class StatisticsApi extends runtime.BaseAPI {
  /**
   * Get current player statistics
   */
  async statisticsControllerGetCurrentPlayerStatisticsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlayerStatisticsDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/statistics`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PlayerStatisticsDtoFromJSON(jsonValue),
    );
  }

  /**
   * Get current player statistics
   */
  async statisticsControllerGetCurrentPlayerStatistics(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlayerStatisticsDto> {
    const response =
      await this.statisticsControllerGetCurrentPlayerStatisticsRaw(
        initOverrides,
      );
    return await response.value();
  }

  /**
   * Get player statistics by id
   */
  async statisticsControllerGetPlayerStatisticsByIdRaw(
    requestParameters: StatisticsControllerGetPlayerStatisticsByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlayerStatisticsDto>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling statisticsControllerGetPlayerStatisticsById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/statistics/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PlayerStatisticsDtoFromJSON(jsonValue),
    );
  }

  /**
   * Get player statistics by id
   */
  async statisticsControllerGetPlayerStatisticsById(
    requestParameters: StatisticsControllerGetPlayerStatisticsByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlayerStatisticsDto> {
    const response = await this.statisticsControllerGetPlayerStatisticsByIdRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
