/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  SearchUserResponseDto,
  UpdateAddUserToBlockedListDto,
  UpdateUserResponse,
  User,
} from "../models/index";
import {
  SearchUserResponseDtoFromJSON,
  SearchUserResponseDtoToJSON,
  UpdateAddUserToBlockedListDtoFromJSON,
  UpdateAddUserToBlockedListDtoToJSON,
  UpdateUserResponseFromJSON,
  UpdateUserResponseToJSON,
  UserFromJSON,
  UserToJSON,
} from "../models/index";

export interface UsersControllerCreateRequest {
  body: object;
}

export interface UsersControllerFindOneRequest {
  id: number;
}

export interface UsersControllerSearchRequest {
  body: object;
}

export interface UsersControllerUpdateRequest {
  body: object;
}

export interface UsersControllerUpdateAddUserToBlockedListRequest {
  updateAddUserToBlockedListDto: UpdateAddUserToBlockedListDto;
}

/**
 *
 */
export class UsersApi extends runtime.BaseAPI {
  /**
   * Create a new user
   */
  async usersControllerCreateRaw(
    requestParameters: UsersControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling usersControllerCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/users`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Create a new user
   */
  async usersControllerCreate(
    requestParameters: UsersControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.usersControllerCreateRaw(requestParameters, initOverrides);
  }

  /**
   * Get a user by ID
   */
  async usersControllerFindOneRaw(
    requestParameters: UsersControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling usersControllerFindOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/users/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserFromJSON(jsonValue),
    );
  }

  /**
   * Get a user by ID
   */
  async usersControllerFindOne(
    requestParameters: UsersControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<User> {
    const response = await this.usersControllerFindOneRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get current user details
   */
  async usersControllerMeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/users/me`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserFromJSON(jsonValue),
    );
  }

  /**
   * Get current user details
   */
  async usersControllerMe(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<User> {
    const response = await this.usersControllerMeRaw(initOverrides);
    return await response.value();
  }

  /**
   * Search for users by nickname or email
   */
  async usersControllerSearchRaw(
    requestParameters: UsersControllerSearchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SearchUserResponseDto>>> {
    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling usersControllerSearch().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/users/search`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SearchUserResponseDtoFromJSON),
    );
  }

  /**
   * Search for users by nickname or email
   */
  async usersControllerSearch(
    requestParameters: UsersControllerSearchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SearchUserResponseDto>> {
    const response = await this.usersControllerSearchRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Update current user details
   */
  async usersControllerUpdateRaw(
    requestParameters: UsersControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUserResponse>> {
    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling usersControllerUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/users/me`,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUserResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update current user details
   */
  async usersControllerUpdate(
    requestParameters: UsersControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUserResponse> {
    const response = await this.usersControllerUpdateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Update add user to blocked list
   */
  async usersControllerUpdateAddUserToBlockedListRaw(
    requestParameters: UsersControllerUpdateAddUserToBlockedListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUserResponse>> {
    if (requestParameters["updateAddUserToBlockedListDto"] == null) {
      throw new runtime.RequiredError(
        "updateAddUserToBlockedListDto",
        'Required parameter "updateAddUserToBlockedListDto" was null or undefined when calling usersControllerUpdateAddUserToBlockedList().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/users/blockUser`,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateAddUserToBlockedListDtoToJSON(
          requestParameters["updateAddUserToBlockedListDto"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUserResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update add user to blocked list
   */
  async usersControllerUpdateAddUserToBlockedList(
    requestParameters: UsersControllerUpdateAddUserToBlockedListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUserResponse> {
    const response = await this.usersControllerUpdateAddUserToBlockedListRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
