/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AcceptInviteResponse
 */
export interface AcceptInviteResponse {
  /**
   * Whether the operation was successful
   * @type {boolean}
   * @memberof AcceptInviteResponse
   */
  success: boolean;
  /**
   * ID of the game room
   * @type {string}
   * @memberof AcceptInviteResponse
   */
  gameRoomId?: string;
  /**
   * Response message
   * @type {string}
   * @memberof AcceptInviteResponse
   */
  message: string;
}

/**
 * Check if a given object implements the AcceptInviteResponse interface.
 */
export function instanceOfAcceptInviteResponse(
  value: object,
): value is AcceptInviteResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function AcceptInviteResponseFromJSON(json: any): AcceptInviteResponse {
  return AcceptInviteResponseFromJSONTyped(json, false);
}

export function AcceptInviteResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AcceptInviteResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    gameRoomId: json["gameRoomId"] == null ? undefined : json["gameRoomId"],
    message: json["message"],
  };
}

export function AcceptInviteResponseToJSON(json: any): AcceptInviteResponse {
  return AcceptInviteResponseToJSONTyped(json, false);
}

export function AcceptInviteResponseToJSONTyped(
  value?: AcceptInviteResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    gameRoomId: value["gameRoomId"],
    message: value["message"],
  };
}
