/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";

/**
 *
 * @export
 * @interface Achievement
 */
export interface Achievement {
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  userId: number;
  /**
   *
   * @type {User}
   * @memberof Achievement
   */
  user: User;
}

/**
 * Check if a given object implements the Achievement interface.
 */
export function instanceOfAchievement(value: object): value is Achievement {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("user" in value) || value["user"] === undefined) return false;
  return true;
}

export function AchievementFromJSON(json: any): Achievement {
  return AchievementFromJSONTyped(json, false);
}

export function AchievementFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Achievement {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["user_id"],
    user: UserFromJSON(json["user"]),
  };
}

export function AchievementToJSON(json: any): Achievement {
  return AchievementToJSONTyped(json, false);
}

export function AchievementToJSONTyped(
  value?: Achievement | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    user_id: value["userId"],
    user: UserToJSON(value["user"]),
  };
}
