/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Achievement } from "./Achievement";
import {
  AchievementFromJSON,
  AchievementFromJSONTyped,
  AchievementToJSON,
  AchievementToJSONTyped,
} from "./Achievement";

/**
 *
 * @export
 * @interface AchievementsResponse
 */
export interface AchievementsResponse {
  /**
   *
   * @type {Array<Achievement>}
   * @memberof AchievementsResponse
   */
  achievements: Array<Achievement>;
}

/**
 * Check if a given object implements the AchievementsResponse interface.
 */
export function instanceOfAchievementsResponse(
  value: object,
): value is AchievementsResponse {
  if (!("achievements" in value) || value["achievements"] === undefined)
    return false;
  return true;
}

export function AchievementsResponseFromJSON(json: any): AchievementsResponse {
  return AchievementsResponseFromJSONTyped(json, false);
}

export function AchievementsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AchievementsResponse {
  if (json == null) {
    return json;
  }
  return {
    achievements: (json["achievements"] as Array<any>).map(AchievementFromJSON),
  };
}

export function AchievementsResponseToJSON(json: any): AchievementsResponse {
  return AchievementsResponseToJSONTyped(json, false);
}

export function AchievementsResponseToJSONTyped(
  value?: AchievementsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    achievements: (value["achievements"] as Array<any>).map(AchievementToJSON),
  };
}
