/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";

/**
 *
 * @export
 * @interface Blocked
 */
export interface Blocked {
  /**
   *
   * @type {number}
   * @memberof Blocked
   */
  id: number;
  /**
   *
   * @type {Date}
   * @memberof Blocked
   */
  blockedTime: Date;
  /**
   *
   * @type {User}
   * @memberof Blocked
   */
  blockedUser: User;
}

/**
 * Check if a given object implements the Blocked interface.
 */
export function instanceOfBlocked(value: object): value is Blocked {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("blockedTime" in value) || value["blockedTime"] === undefined)
    return false;
  if (!("blockedUser" in value) || value["blockedUser"] === undefined)
    return false;
  return true;
}

export function BlockedFromJSON(json: any): Blocked {
  return BlockedFromJSONTyped(json, false);
}

export function BlockedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Blocked {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    blockedTime: new Date(json["blocked_time"]),
    blockedUser: UserFromJSON(json["blockedUser"]),
  };
}

export function BlockedToJSON(json: any): Blocked {
  return BlockedToJSONTyped(json, false);
}

export function BlockedToJSONTyped(
  value?: Blocked | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    blocked_time: value["blockedTime"].toISOString(),
    blockedUser: UserToJSON(value["blockedUser"]),
  };
}
