/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Blocked
 */
export interface Blocked {
    /**
     * 
     * @type {Date}
     * @memberof Blocked
     */
    blockedTime: Date;
    /**
     * 
     * @type {number}
     * @memberof Blocked
     */
    blockedUserId: number;
    /**
     * 
     * @type {number}
     * @memberof Blocked
     */
    userId: number;
    /**
     * 
     * @type {User}
     * @memberof Blocked
     */
    blockedUser: User;
    /**
     * 
     * @type {User}
     * @memberof Blocked
     */
    user: User;
}

/**
 * Check if a given object implements the Blocked interface.
 */
export function instanceOfBlocked(value: object): value is Blocked {
    if (!('blockedTime' in value) || value['blockedTime'] === undefined) return false;
    if (!('blockedUserId' in value) || value['blockedUserId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('blockedUser' in value) || value['blockedUser'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function BlockedFromJSON(json: any): Blocked {
    return BlockedFromJSONTyped(json, false);
}

export function BlockedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Blocked {
    if (json == null) {
        return json;
    }
    return {
        
        'blockedTime': (new Date(json['blocked_time'])),
        'blockedUserId': json['blocked_user_id'],
        'userId': json['user_id'],
        'blockedUser': UserFromJSON(json['blockedUser']),
        'user': UserFromJSON(json['user']),
    };
}

export function BlockedToJSON(json: any): Blocked {
    return BlockedToJSONTyped(json, false);
}

export function BlockedToJSONTyped(value?: Blocked | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocked_time': ((value['blockedTime']).toISOString()),
        'blocked_user_id': value['blockedUserId'],
        'user_id': value['userId'],
        'blockedUser': UserToJSON(value['blockedUser']),
        'user': UserToJSON(value['user']),
    };
}

