/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";
import type { ChatRoom } from "./ChatRoom";
import {
  ChatRoomFromJSON,
  ChatRoomFromJSONTyped,
  ChatRoomToJSON,
  ChatRoomToJSONTyped,
} from "./ChatRoom";

/**
 *
 * @export
 * @interface ChatParticipant
 */
export interface ChatParticipant {
  /**
   *
   * @type {string}
   * @memberof ChatParticipant
   */
  chatParticipantRole: ChatParticipantChatParticipantRoleEnum;
  /**
   *
   * @type {boolean}
   * @memberof ChatParticipant
   */
  isBanned: boolean;
  /**
   *
   * @type {Date}
   * @memberof ChatParticipant
   */
  bannedUntil: Date;
  /**
   *
   * @type {boolean}
   * @memberof ChatParticipant
   */
  isMuted: boolean;
  /**
   *
   * @type {Date}
   * @memberof ChatParticipant
   */
  createdAt: Date;
  /**
   *
   * @type {number}
   * @memberof ChatParticipant
   */
  userId: number;
  /**
   *
   * @type {number}
   * @memberof ChatParticipant
   */
  chatRoomId: number;
  /**
   *
   * @type {User}
   * @memberof ChatParticipant
   */
  user: User;
  /**
   *
   * @type {ChatRoom}
   * @memberof ChatParticipant
   */
  chatRoom: ChatRoom;
}

/**
 * @export
 */
export const ChatParticipantChatParticipantRoleEnum = {
  Owner: "owner",
  Admin: "admin",
  Guest: "guest",
} as const;
export type ChatParticipantChatParticipantRoleEnum =
  (typeof ChatParticipantChatParticipantRoleEnum)[keyof typeof ChatParticipantChatParticipantRoleEnum];

/**
 * Check if a given object implements the ChatParticipant interface.
 */
export function instanceOfChatParticipant(
  value: object,
): value is ChatParticipant {
  if (
    !("chatParticipantRole" in value) ||
    value["chatParticipantRole"] === undefined
  )
    return false;
  if (!("isBanned" in value) || value["isBanned"] === undefined) return false;
  if (!("bannedUntil" in value) || value["bannedUntil"] === undefined)
    return false;
  if (!("isMuted" in value) || value["isMuted"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("chatRoomId" in value) || value["chatRoomId"] === undefined)
    return false;
  if (!("user" in value) || value["user"] === undefined) return false;
  if (!("chatRoom" in value) || value["chatRoom"] === undefined) return false;
  return true;
}

export function ChatParticipantFromJSON(json: any): ChatParticipant {
  return ChatParticipantFromJSONTyped(json, false);
}

export function ChatParticipantFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatParticipant {
  if (json == null) {
    return json;
  }
  return {
    chatParticipantRole: json["chat_participant_role"],
    isBanned: json["is_banned"],
    bannedUntil: new Date(json["banned_until"]),
    isMuted: json["is_muted"],
    createdAt: new Date(json["created_at"]),
    userId: json["user_id"],
    chatRoomId: json["chat_room_id"],
    user: UserFromJSON(json["user"]),
    chatRoom: ChatRoomFromJSON(json["chatRoom"]),
  };
}

export function ChatParticipantToJSON(json: any): ChatParticipant {
  return ChatParticipantToJSONTyped(json, false);
}

export function ChatParticipantToJSONTyped(
  value?: ChatParticipant | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chat_participant_role: value["chatParticipantRole"],
    is_banned: value["isBanned"],
    banned_until: value["bannedUntil"].toISOString(),
    is_muted: value["isMuted"],
    created_at: value["createdAt"].toISOString(),
    user_id: value["userId"],
    chat_room_id: value["chatRoomId"],
    user: UserToJSON(value["user"]),
    chatRoom: ChatRoomToJSON(value["chatRoom"]),
  };
}
