/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ChatParticipant } from "./ChatParticipant";
import {
  ChatParticipantFromJSON,
  ChatParticipantFromJSONTyped,
  ChatParticipantToJSON,
  ChatParticipantToJSONTyped,
} from "./ChatParticipant";

/**
 *
 * @export
 * @interface ChatParticipantsResponse
 */
export interface ChatParticipantsResponse {
  /**
   *
   * @type {boolean}
   * @memberof ChatParticipantsResponse
   */
  success: boolean;
  /**
   *
   * @type {Array<ChatParticipant>}
   * @memberof ChatParticipantsResponse
   */
  chatParticipants: Array<ChatParticipant>;
  /**
   *
   * @type {string}
   * @memberof ChatParticipantsResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ChatParticipantsResponse interface.
 */
export function instanceOfChatParticipantsResponse(
  value: object,
): value is ChatParticipantsResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("chatParticipants" in value) || value["chatParticipants"] === undefined)
    return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function ChatParticipantsResponseFromJSON(
  json: any,
): ChatParticipantsResponse {
  return ChatParticipantsResponseFromJSONTyped(json, false);
}

export function ChatParticipantsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatParticipantsResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    chatParticipants: (json["chatParticipants"] as Array<any>).map(
      ChatParticipantFromJSON,
    ),
    message: json["message"],
  };
}

export function ChatParticipantsResponseToJSON(
  json: any,
): ChatParticipantsResponse {
  return ChatParticipantsResponseToJSONTyped(json, false);
}

export function ChatParticipantsResponseToJSONTyped(
  value?: ChatParticipantsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    chatParticipants: (value["chatParticipants"] as Array<any>).map(
      ChatParticipantToJSON,
    ),
    message: value["message"],
  };
}
