/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ChatParticipant } from "./ChatParticipant";
import {
  ChatParticipantFromJSON,
  ChatParticipantFromJSONTyped,
  ChatParticipantToJSON,
  ChatParticipantToJSONTyped,
} from "./ChatParticipant";

/**
 *
 * @export
 * @interface ChatParticipantResponse
 */
export interface ChatParticipantResponse {
  /**
   *
   * @type {boolean}
   * @memberof ChatParticipantResponse
   */
  success: boolean;
  /**
   *
   * @type {ChatParticipant}
   * @memberof ChatParticipantResponse
   */
  chatParticipant: ChatParticipant;
  /**
   *
   * @type {string}
   * @memberof ChatParticipantResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ChatParticipantResponse interface.
 */
export function instanceOfChatParticipantResponse(
  value: object,
): value is ChatParticipantResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("chatParticipant" in value) || value["chatParticipant"] === undefined)
    return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function ChatParticipantResponseFromJSON(
  json: any,
): ChatParticipantResponse {
  return ChatParticipantResponseFromJSONTyped(json, false);
}

export function ChatParticipantResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatParticipantResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    chatParticipant: ChatParticipantFromJSON(json["chatParticipant"]),
    message: json["message"],
  };
}

export function ChatParticipantResponseToJSON(
  json: any,
): ChatParticipantResponse {
  return ChatParticipantResponseToJSONTyped(json, false);
}

export function ChatParticipantResponseToJSONTyped(
  value?: ChatParticipantResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    chatParticipant: ChatParticipantToJSON(value["chatParticipant"]),
    message: value["message"],
  };
}
