/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChatRoomsResponse
 */
export interface ChatRoomsResponse {
  /**
   *
   * @type {boolean}
   * @memberof ChatRoomsResponse
   */
  success: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof ChatRoomsResponse
   */
  chatRooms: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ChatRoomsResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ChatRoomsResponse interface.
 */
export function instanceOfChatRoomsResponse(
  value: object,
): value is ChatRoomsResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("chatRooms" in value) || value["chatRooms"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function ChatRoomsResponseFromJSON(json: any): ChatRoomsResponse {
  return ChatRoomsResponseFromJSONTyped(json, false);
}

export function ChatRoomsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatRoomsResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    chatRooms: json["chatRooms"],
    message: json["message"],
  };
}

export function ChatRoomsResponseToJSON(json: any): ChatRoomsResponse {
  return ChatRoomsResponseToJSONTyped(json, false);
}

export function ChatRoomsResponseToJSONTyped(
  value?: ChatRoomsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    chatRooms: value["chatRooms"],
    message: value["message"],
  };
}
