/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ChatRoom } from "./ChatRoom";
import {
  ChatRoomFromJSON,
  ChatRoomFromJSONTyped,
  ChatRoomToJSON,
  ChatRoomToJSONTyped,
} from "./ChatRoom";

/**
 *
 * @export
 * @interface ChatRoomResponse
 */
export interface ChatRoomResponse {
  /**
   *
   * @type {boolean}
   * @memberof ChatRoomResponse
   */
  success: boolean;
  /**
   *
   * @type {ChatRoom}
   * @memberof ChatRoomResponse
   */
  chatRoom?: ChatRoom;
  /**
   *
   * @type {string}
   * @memberof ChatRoomResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the ChatRoomResponse interface.
 */
export function instanceOfChatRoomResponse(
  value: object,
): value is ChatRoomResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  return true;
}

export function ChatRoomResponseFromJSON(json: any): ChatRoomResponse {
  return ChatRoomResponseFromJSONTyped(json, false);
}

export function ChatRoomResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatRoomResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    chatRoom:
      json["chatRoom"] == null ? undefined : ChatRoomFromJSON(json["chatRoom"]),
    message: json["message"] == null ? undefined : json["message"],
  };
}

export function ChatRoomResponseToJSON(json: any): ChatRoomResponse {
  return ChatRoomResponseToJSONTyped(json, false);
}

export function ChatRoomResponseToJSONTyped(
  value?: ChatRoomResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    chatRoom: ChatRoomToJSON(value["chatRoom"]),
    message: value["message"],
  };
}
