/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ChatMessage } from "./ChatMessage";
import {
  ChatMessageFromJSON,
  ChatMessageFromJSONTyped,
  ChatMessageToJSON,
  ChatMessageToJSONTyped,
} from "./ChatMessage";
import type { ChatParticipant } from "./ChatParticipant";
import {
  ChatParticipantFromJSON,
  ChatParticipantFromJSONTyped,
  ChatParticipantToJSON,
  ChatParticipantToJSONTyped,
} from "./ChatParticipant";

/**
 *
 * @export
 * @interface ChatRoom
 */
export interface ChatRoom {
  /**
   *
   * @type {number}
   * @memberof ChatRoom
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  password: string;
  /**
   *
   * @type {Date}
   * @memberof ChatRoom
   */
  creationDate: Date;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  chatRoomType: ChatRoomChatRoomTypeEnum;
  /**
   *
   * @type {Array<ChatMessage>}
   * @memberof ChatRoom
   */
  chatMessages: Array<ChatMessage>;
  /**
   *
   * @type {Array<ChatParticipant>}
   * @memberof ChatRoom
   */
  chatParticipants: Array<ChatParticipant>;
}

/**
 * @export
 */
export const ChatRoomChatRoomTypeEnum = {
  Public: "public",
  Protected: "protected",
  Private: "private",
  Dm: "Dm",
} as const;
export type ChatRoomChatRoomTypeEnum =
  (typeof ChatRoomChatRoomTypeEnum)[keyof typeof ChatRoomChatRoomTypeEnum];

/**
 * Check if a given object implements the ChatRoom interface.
 */
export function instanceOfChatRoom(value: object): value is ChatRoom {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  if (!("creationDate" in value) || value["creationDate"] === undefined)
    return false;
  if (!("chatRoomType" in value) || value["chatRoomType"] === undefined)
    return false;
  if (!("chatMessages" in value) || value["chatMessages"] === undefined)
    return false;
  if (!("chatParticipants" in value) || value["chatParticipants"] === undefined)
    return false;
  return true;
}

export function ChatRoomFromJSON(json: any): ChatRoom {
  return ChatRoomFromJSONTyped(json, false);
}

export function ChatRoomFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatRoom {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    password: json["password"],
    creationDate: new Date(json["creation_date"]),
    chatRoomType: json["chat_room_type"],
    chatMessages: (json["chatMessages"] as Array<any>).map(ChatMessageFromJSON),
    chatParticipants: (json["chatParticipants"] as Array<any>).map(
      ChatParticipantFromJSON,
    ),
  };
}

export function ChatRoomToJSON(json: any): ChatRoom {
  return ChatRoomToJSONTyped(json, false);
}

export function ChatRoomToJSONTyped(
  value?: ChatRoom | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    password: value["password"],
    creation_date: value["creationDate"].toISOString(),
    chat_room_type: value["chatRoomType"],
    chatMessages: (value["chatMessages"] as Array<any>).map(ChatMessageToJSON),
    chatParticipants: (value["chatParticipants"] as Array<any>).map(
      ChatParticipantToJSON,
    ),
  };
}
