/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CheckPasswordDto
 */
export interface CheckPasswordDto {
  /**
   * input password
   * @type {string}
   * @memberof CheckPasswordDto
   */
  password: string;
  /**
   * chat room to check
   * @type {number}
   * @memberof CheckPasswordDto
   */
  chatRoomId: number;
}

/**
 * Check if a given object implements the CheckPasswordDto interface.
 */
export function instanceOfCheckPasswordDto(
  value: object,
): value is CheckPasswordDto {
  if (!("password" in value) || value["password"] === undefined) return false;
  if (!("chatRoomId" in value) || value["chatRoomId"] === undefined)
    return false;
  return true;
}

export function CheckPasswordDtoFromJSON(json: any): CheckPasswordDto {
  return CheckPasswordDtoFromJSONTyped(json, false);
}

export function CheckPasswordDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckPasswordDto {
  if (json == null) {
    return json;
  }
  return {
    password: json["password"],
    chatRoomId: json["chatRoomId"],
  };
}

export function CheckPasswordDtoToJSON(json: any): CheckPasswordDto {
  return CheckPasswordDtoToJSONTyped(json, false);
}

export function CheckPasswordDtoToJSONTyped(
  value?: CheckPasswordDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    password: value["password"],
    chatRoomId: value["chatRoomId"],
  };
}
