/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";

/**
 *
 * @export
 * @interface CreateBlockedDto
 */
export interface CreateBlockedDto {
  /**
   * blocked_time
   * @type {Date}
   * @memberof CreateBlockedDto
   */
  blockedTime: Date;
  /**
   * blocked_user_id
   * @type {User}
   * @memberof CreateBlockedDto
   */
  blockedUser: User;
}

/**
 * Check if a given object implements the CreateBlockedDto interface.
 */
export function instanceOfCreateBlockedDto(
  value: object,
): value is CreateBlockedDto {
  if (!("blockedTime" in value) || value["blockedTime"] === undefined)
    return false;
  if (!("blockedUser" in value) || value["blockedUser"] === undefined)
    return false;
  return true;
}

export function CreateBlockedDtoFromJSON(json: any): CreateBlockedDto {
  return CreateBlockedDtoFromJSONTyped(json, false);
}

export function CreateBlockedDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateBlockedDto {
  if (json == null) {
    return json;
  }
  return {
    blockedTime: new Date(json["blocked_time"]),
    blockedUser: UserFromJSON(json["blockedUser"]),
  };
}

export function CreateBlockedDtoToJSON(json: any): CreateBlockedDto {
  return CreateBlockedDtoToJSONTyped(json, false);
}

export function CreateBlockedDtoToJSONTyped(
  value?: CreateBlockedDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    blocked_time: value["blockedTime"].toISOString(),
    blockedUser: UserToJSON(value["blockedUser"]),
  };
}
