/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateInviteDto
 */
export interface CreateInviteDto {
  /**
   * ID of the user to invite
   * @type {number}
   * @memberof CreateInviteDto
   */
  receiverUserId: number;
}

/**
 * Check if a given object implements the CreateInviteDto interface.
 */
export function instanceOfCreateInviteDto(
  value: object,
): value is CreateInviteDto {
  if (!("receiverUserId" in value) || value["receiverUserId"] === undefined)
    return false;
  return true;
}

export function CreateInviteDtoFromJSON(json: any): CreateInviteDto {
  return CreateInviteDtoFromJSONTyped(json, false);
}

export function CreateInviteDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateInviteDto {
  if (json == null) {
    return json;
  }
  return {
    receiverUserId: json["receiverUserId"],
  };
}

export function CreateInviteDtoToJSON(json: any): CreateInviteDto {
  return CreateInviteDtoToJSONTyped(json, false);
}

export function CreateInviteDtoToJSONTyped(
  value?: CreateInviteDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    receiverUserId: value["receiverUserId"],
  };
}
