/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
  /**
   * User avatar
   * @type {string}
   * @memberof CreateUserDto
   */
  avatar: string;
  /**
   * User nickname
   * @type {string}
   * @memberof CreateUserDto
   */
  nickname: string;
  /**
   * enable two factor authentication
   * @type {boolean}
   * @memberof CreateUserDto
   */
  twoFactorEnabled: boolean;
  /**
   * Second authentication status
   * @type {boolean}
   * @memberof CreateUserDto
   */
  isSecondAuthDone: boolean;
  /**
   * Two factor authentication secret
   * @type {string}
   * @memberof CreateUserDto
   */
  twoFactorAuthSecret: string;
  /**
   * email address
   * @type {string}
   * @memberof CreateUserDto
   */
  email: string;
  /**
   * Ladder level
   * @type {number}
   * @memberof CreateUserDto
   */
  ladderLevel: number;
  /**
   * User status
   * @type {string}
   * @memberof CreateUserDto
   */
  userStatus: CreateUserDtoUserStatusEnum;
}

/**
 * @export
 */
export const CreateUserDtoUserStatusEnum = {
  Offline: "offline",
  Online: "online",
  Waiting: "waiting",
  Playing: "playing",
} as const;
export type CreateUserDtoUserStatusEnum =
  (typeof CreateUserDtoUserStatusEnum)[keyof typeof CreateUserDtoUserStatusEnum];

/**
 * Check if a given object implements the CreateUserDto interface.
 */
export function instanceOfCreateUserDto(value: object): value is CreateUserDto {
  if (!("avatar" in value) || value["avatar"] === undefined) return false;
  if (!("nickname" in value) || value["nickname"] === undefined) return false;
  if (!("twoFactorEnabled" in value) || value["twoFactorEnabled"] === undefined)
    return false;
  if (!("isSecondAuthDone" in value) || value["isSecondAuthDone"] === undefined)
    return false;
  if (
    !("twoFactorAuthSecret" in value) ||
    value["twoFactorAuthSecret"] === undefined
  )
    return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("ladderLevel" in value) || value["ladderLevel"] === undefined)
    return false;
  if (!("userStatus" in value) || value["userStatus"] === undefined)
    return false;
  return true;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
  return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateUserDto {
  if (json == null) {
    return json;
  }
  return {
    avatar: json["avatar"],
    nickname: json["nickname"],
    twoFactorEnabled: json["two_factor_enabled"],
    isSecondAuthDone: json["is_second_auth_done"],
    twoFactorAuthSecret: json["two_factor_auth_secret"],
    email: json["email"],
    ladderLevel: json["ladder_level"],
    userStatus: json["user_status"],
  };
}

export function CreateUserDtoToJSON(json: any): CreateUserDto {
  return CreateUserDtoToJSONTyped(json, false);
}

export function CreateUserDtoToJSONTyped(
  value?: CreateUserDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    avatar: value["avatar"],
    nickname: value["nickname"],
    two_factor_enabled: value["twoFactorEnabled"],
    is_second_auth_done: value["isSecondAuthDone"],
    two_factor_auth_secret: value["twoFactorAuthSecret"],
    email: value["email"],
    ladder_level: value["ladderLevel"],
    user_status: value["userStatus"],
  };
}
