/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateGameDto
 */
export interface CreateGameDto {
  /**
   * Room identifier
   * @type {string}
   * @memberof CreateGameDto
   */
  roomIdentifier: string;
  /**
   * Game status
   * @type {string}
   * @memberof CreateGameDto
   */
  status: CreateGameDtoStatusEnum;
  /**
   * Player 1 ID
   * @type {number}
   * @memberof CreateGameDto
   */
  player1UserId: number;
  /**
   * Player 2 ID
   * @type {number}
   * @memberof CreateGameDto
   */
  player2UserId: number;
  /**
   * Winner ID
   * @type {number}
   * @memberof CreateGameDto
   */
  winnerUserId: number;
  /**
   * Game score
   * @type {Array<number>}
   * @memberof CreateGameDto
   */
  score: Array<number>;
  /**
   * Game end time
   * @type {Date}
   * @memberof CreateGameDto
   */
  endedAt?: Date;
  /**
   * Game creation time
   * @type {Date}
   * @memberof CreateGameDto
   */
  createdAt: Date;
  /**
   * Invite Id
   * @type {number}
   * @memberof CreateGameDto
   */
  inviteId: number;
}

/**
 * @export
 */
export const CreateGameDtoStatusEnum = {
  Pending: "pending",
  Countdown: "countdown",
  Ongoing: "ongoing",
  Closed: "closed",
  Cancelled: "cancelled",
} as const;
export type CreateGameDtoStatusEnum =
  (typeof CreateGameDtoStatusEnum)[keyof typeof CreateGameDtoStatusEnum];

/**
 * Check if a given object implements the CreateGameDto interface.
 */
export function instanceOfCreateGameDto(value: object): value is CreateGameDto {
  if (!("roomIdentifier" in value) || value["roomIdentifier"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("player1UserId" in value) || value["player1UserId"] === undefined)
    return false;
  if (!("player2UserId" in value) || value["player2UserId"] === undefined)
    return false;
  if (!("winnerUserId" in value) || value["winnerUserId"] === undefined)
    return false;
  if (!("score" in value) || value["score"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("inviteId" in value) || value["inviteId"] === undefined) return false;
  return true;
}

export function CreateGameDtoFromJSON(json: any): CreateGameDto {
  return CreateGameDtoFromJSONTyped(json, false);
}

export function CreateGameDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateGameDto {
  if (json == null) {
    return json;
  }
  return {
    roomIdentifier: json["room_identifier"],
    status: json["status"],
    player1UserId: json["player1_user_id"],
    player2UserId: json["player2_user_id"],
    winnerUserId: json["winner_user_id"],
    score: json["score"],
    endedAt: json["ended_at"] == null ? undefined : new Date(json["ended_at"]),
    createdAt: new Date(json["created_at"]),
    inviteId: json["invite_id"],
  };
}

export function CreateGameDtoToJSON(json: any): CreateGameDto {
  return CreateGameDtoToJSONTyped(json, false);
}

export function CreateGameDtoToJSONTyped(
  value?: CreateGameDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    room_identifier: value["roomIdentifier"],
    status: value["status"],
    player1_user_id: value["player1UserId"],
    player2_user_id: value["player2UserId"],
    winner_user_id: value["winnerUserId"],
    score: value["score"],
    ended_at:
      value["endedAt"] == null ? undefined : value["endedAt"].toISOString(),
    created_at: value["createdAt"].toISOString(),
    invite_id: value["inviteId"],
  };
}
