/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateChatParticipantDto
 */
export interface CreateChatParticipantDto {
  /**
   * Chat participant role
   * @type {string}
   * @memberof CreateChatParticipantDto
   */
  chatParticipantRole?: CreateChatParticipantDtoChatParticipantRoleEnum;
  /**
   * left at this date
   * @type {Date}
   * @memberof CreateChatParticipantDto
   */
  leftAt?: Date;
  /**
   * Is banned
   * @type {boolean}
   * @memberof CreateChatParticipantDto
   */
  isBanned?: boolean;
  /**
   * Is muted
   * @type {boolean}
   * @memberof CreateChatParticipantDto
   */
  isMuted?: boolean;
  /**
   * Entrance time
   * @type {Date}
   * @memberof CreateChatParticipantDto
   */
  entranceTime?: Date;
  /**
   * User ID
   * @type {number}
   * @memberof CreateChatParticipantDto
   */
  userId: number;
  /**
   * Chat room ID
   * @type {number}
   * @memberof CreateChatParticipantDto
   */
  chatRoomId: number;
}

/**
 * @export
 */
export const CreateChatParticipantDtoChatParticipantRoleEnum = {
  Owner: "owner",
  Admin: "admin",
  Guest: "guest",
} as const;
export type CreateChatParticipantDtoChatParticipantRoleEnum =
  (typeof CreateChatParticipantDtoChatParticipantRoleEnum)[keyof typeof CreateChatParticipantDtoChatParticipantRoleEnum];

/**
 * Check if a given object implements the CreateChatParticipantDto interface.
 */
export function instanceOfCreateChatParticipantDto(
  value: object,
): value is CreateChatParticipantDto {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("chatRoomId" in value) || value["chatRoomId"] === undefined)
    return false;
  return true;
}

export function CreateChatParticipantDtoFromJSON(
  json: any,
): CreateChatParticipantDto {
  return CreateChatParticipantDtoFromJSONTyped(json, false);
}

export function CreateChatParticipantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateChatParticipantDto {
  if (json == null) {
    return json;
  }
  return {
    chatParticipantRole:
      json["chat_participant_role"] == null
        ? undefined
        : json["chat_participant_role"],
    leftAt: json["leftAt"] == null ? undefined : new Date(json["leftAt"]),
    isBanned: json["is_banned"] == null ? undefined : json["is_banned"],
    isMuted: json["is_muted"] == null ? undefined : json["is_muted"],
    entranceTime:
      json["entrance_time"] == null
        ? undefined
        : new Date(json["entrance_time"]),
    userId: json["user_id"],
    chatRoomId: json["chat_room_id"],
  };
}

export function CreateChatParticipantDtoToJSON(
  json: any,
): CreateChatParticipantDto {
  return CreateChatParticipantDtoToJSONTyped(json, false);
}

export function CreateChatParticipantDtoToJSONTyped(
  value?: CreateChatParticipantDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chat_participant_role: value["chatParticipantRole"],
    leftAt: value["leftAt"] == null ? undefined : value["leftAt"].toISOString(),
    is_banned: value["isBanned"],
    is_muted: value["isMuted"],
    entrance_time:
      value["entranceTime"] == null
        ? undefined
        : value["entranceTime"].toISOString(),
    user_id: value["userId"],
    chat_room_id: value["chatRoomId"],
  };
}
