/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DevLoginResponseDto
 */
export interface DevLoginResponseDto {
  /**
   *
   * @type {string}
   * @memberof DevLoginResponseDto
   */
  accessToken: string;
}

/**
 * Check if a given object implements the DevLoginResponseDto interface.
 */
export function instanceOfDevLoginResponseDto(
  value: object,
): value is DevLoginResponseDto {
  if (!("accessToken" in value) || value["accessToken"] === undefined)
    return false;
  return true;
}

export function DevLoginResponseDtoFromJSON(json: any): DevLoginResponseDto {
  return DevLoginResponseDtoFromJSONTyped(json, false);
}

export function DevLoginResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DevLoginResponseDto {
  if (json == null) {
    return json;
  }
  return {
    accessToken: json["accessToken"],
  };
}

export function DevLoginResponseDtoToJSON(json: any): DevLoginResponseDto {
  return DevLoginResponseDtoToJSONTyped(json, false);
}

export function DevLoginResponseDtoToJSONTyped(
  value?: DevLoginResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    accessToken: value["accessToken"],
  };
}
