/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FileUploadResponseSuccess
 */
export interface FileUploadResponseSuccess {
  /**
   *
   * @type {string}
   * @memberof FileUploadResponseSuccess
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof FileUploadResponseSuccess
   */
  filePath: string;
}

/**
 * Check if a given object implements the FileUploadResponseSuccess interface.
 */
export function instanceOfFileUploadResponseSuccess(
  value: object,
): value is FileUploadResponseSuccess {
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("filePath" in value) || value["filePath"] === undefined) return false;
  return true;
}

export function FileUploadResponseSuccessFromJSON(
  json: any,
): FileUploadResponseSuccess {
  return FileUploadResponseSuccessFromJSONTyped(json, false);
}

export function FileUploadResponseSuccessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FileUploadResponseSuccess {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"],
    filePath: json["filePath"],
  };
}

export function FileUploadResponseSuccessToJSON(
  json: any,
): FileUploadResponseSuccess {
  return FileUploadResponseSuccessToJSONTyped(json, false);
}

export function FileUploadResponseSuccessToJSONTyped(
  value?: FileUploadResponseSuccess | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
    filePath: value["filePath"],
  };
}
