/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FindChatMessageDto
 */
export interface FindChatMessageDto {
  /**
   *
   * @type {number}
   * @memberof FindChatMessageDto
   */
  chatRoomId?: number;
  /**
   *
   * @type {Date}
   * @memberof FindChatMessageDto
   */
  sentTimeFrom?: Date;
  /**
   *
   * @type {Date}
   * @memberof FindChatMessageDto
   */
  sentTimeTill?: Date;
}

/**
 * Check if a given object implements the FindChatMessageDto interface.
 */
export function instanceOfFindChatMessageDto(
  value: object,
): value is FindChatMessageDto {
  return true;
}

export function FindChatMessageDtoFromJSON(json: any): FindChatMessageDto {
  return FindChatMessageDtoFromJSONTyped(json, false);
}

export function FindChatMessageDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FindChatMessageDto {
  if (json == null) {
    return json;
  }
  return {
    chatRoomId: json["chatRoomId"] == null ? undefined : json["chatRoomId"],
    sentTimeFrom:
      json["sent_time_from"] == null
        ? undefined
        : new Date(json["sent_time_from"]),
    sentTimeTill:
      json["sent_time_till"] == null
        ? undefined
        : new Date(json["sent_time_till"]),
  };
}

export function FindChatMessageDtoToJSON(json: any): FindChatMessageDto {
  return FindChatMessageDtoToJSONTyped(json, false);
}

export function FindChatMessageDtoToJSONTyped(
  value?: FindChatMessageDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chatRoomId: value["chatRoomId"],
    sent_time_from:
      value["sentTimeFrom"] == null
        ? undefined
        : value["sentTimeFrom"].toISOString(),
    sent_time_till:
      value["sentTimeTill"] == null
        ? undefined
        : value["sentTimeTill"].toISOString(),
  };
}
