/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FindChatMessageDto
 */
export interface FindChatMessageDto {
  /**
   * chatRoomId
   * @type {number}
   * @memberof FindChatMessageDto
   */
  chatRoomId: number;
  /**
   * daysAgo
   * @type {number}
   * @memberof FindChatMessageDto
   */
  daysAgo: number;
}

/**
 * Check if a given object implements the FindChatMessageDto interface.
 */
export function instanceOfFindChatMessageDto(
  value: object,
): value is FindChatMessageDto {
  if (!("chatRoomId" in value) || value["chatRoomId"] === undefined)
    return false;
  if (!("daysAgo" in value) || value["daysAgo"] === undefined) return false;
  return true;
}

export function FindChatMessageDtoFromJSON(json: any): FindChatMessageDto {
  return FindChatMessageDtoFromJSONTyped(json, false);
}

export function FindChatMessageDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FindChatMessageDto {
  if (json == null) {
    return json;
  }
  return {
    chatRoomId: json["chatRoomId"],
    daysAgo: json["daysAgo"],
  };
}

export function FindChatMessageDtoToJSON(json: any): FindChatMessageDto {
  return FindChatMessageDtoToJSONTyped(json, false);
}

export function FindChatMessageDtoToJSONTyped(
  value?: FindChatMessageDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chatRoomId: value["chatRoomId"],
    daysAgo: value["daysAgo"],
  };
}
