/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FriendsControllerGetFriendStatus200Response
 */
export interface FriendsControllerGetFriendStatus200Response {
  /**
   *
   * @type {boolean}
   * @memberof FriendsControllerGetFriendStatus200Response
   */
  success?: boolean;
  /**
   *
   * @type {string}
   * @memberof FriendsControllerGetFriendStatus200Response
   */
  friendStatus?: FriendsControllerGetFriendStatus200ResponseFriendStatusEnum;
}

/**
 * @export
 */
export const FriendsControllerGetFriendStatus200ResponseFriendStatusEnum = {
  Pending: "pending",
  Accepted: "accepted",
  Rejected: "rejected",
  NotFriends: "not_friends",
} as const;
export type FriendsControllerGetFriendStatus200ResponseFriendStatusEnum =
  (typeof FriendsControllerGetFriendStatus200ResponseFriendStatusEnum)[keyof typeof FriendsControllerGetFriendStatus200ResponseFriendStatusEnum];

/**
 * Check if a given object implements the FriendsControllerGetFriendStatus200Response interface.
 */
export function instanceOfFriendsControllerGetFriendStatus200Response(
  value: object,
): value is FriendsControllerGetFriendStatus200Response {
  return true;
}

export function FriendsControllerGetFriendStatus200ResponseFromJSON(
  json: any,
): FriendsControllerGetFriendStatus200Response {
  return FriendsControllerGetFriendStatus200ResponseFromJSONTyped(json, false);
}

export function FriendsControllerGetFriendStatus200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FriendsControllerGetFriendStatus200Response {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"] == null ? undefined : json["success"],
    friendStatus:
      json["friendStatus"] == null ? undefined : json["friendStatus"],
  };
}

export function FriendsControllerGetFriendStatus200ResponseToJSON(
  json: any,
): FriendsControllerGetFriendStatus200Response {
  return FriendsControllerGetFriendStatus200ResponseToJSONTyped(json, false);
}

export function FriendsControllerGetFriendStatus200ResponseToJSONTyped(
  value?: FriendsControllerGetFriendStatus200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    friendStatus: value["friendStatus"],
  };
}
