/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Friend
 */
export interface Friend {
    /**
     * 
     * @type {number}
     * @memberof Friend
     */
    person1UserId: number;
    /**
     * 
     * @type {number}
     * @memberof Friend
     */
    person2UserId: number;
    /**
     * 
     * @type {User}
     * @memberof Friend
     */
    person1User: User;
    /**
     * 
     * @type {User}
     * @memberof Friend
     */
    person2User: User;
}

/**
 * Check if a given object implements the Friend interface.
 */
export function instanceOfFriend(value: object): value is Friend {
    if (!('person1UserId' in value) || value['person1UserId'] === undefined) return false;
    if (!('person2UserId' in value) || value['person2UserId'] === undefined) return false;
    if (!('person1User' in value) || value['person1User'] === undefined) return false;
    if (!('person2User' in value) || value['person2User'] === undefined) return false;
    return true;
}

export function FriendFromJSON(json: any): Friend {
    return FriendFromJSONTyped(json, false);
}

export function FriendFromJSONTyped(json: any, ignoreDiscriminator: boolean): Friend {
    if (json == null) {
        return json;
    }
    return {
        
        'person1UserId': json['person1_user_id'],
        'person2UserId': json['person2_user_id'],
        'person1User': UserFromJSON(json['person1User']),
        'person2User': UserFromJSON(json['person2User']),
    };
}

export function FriendToJSON(json: any): Friend {
    return FriendToJSONTyped(json, false);
}

export function FriendToJSONTyped(value?: Friend | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person1_user_id': value['person1UserId'],
        'person2_user_id': value['person2UserId'],
        'person1User': UserToJSON(value['person1User']),
        'person2User': UserToJSON(value['person2User']),
    };
}

