/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";

/**
 *
 * @export
 * @interface Friend
 */
export interface Friend {
  /**
   *
   * @type {number}
   * @memberof Friend
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Friend
   */
  senderId: number;
  /**
   *
   * @type {number}
   * @memberof Friend
   */
  receiverId: number;
  /**
   *
   * @type {string}
   * @memberof Friend
   */
  status: FriendStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof Friend
   */
  createdAt: Date;
  /**
   *
   * @type {User}
   * @memberof Friend
   */
  sender: User;
  /**
   *
   * @type {User}
   * @memberof Friend
   */
  receiver: User;
}

/**
 * @export
 */
export const FriendStatusEnum = {
  Pending: "pending",
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
export type FriendStatusEnum =
  (typeof FriendStatusEnum)[keyof typeof FriendStatusEnum];

/**
 * Check if a given object implements the Friend interface.
 */
export function instanceOfFriend(value: object): value is Friend {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("senderId" in value) || value["senderId"] === undefined) return false;
  if (!("receiverId" in value) || value["receiverId"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("sender" in value) || value["sender"] === undefined) return false;
  if (!("receiver" in value) || value["receiver"] === undefined) return false;
  return true;
}

export function FriendFromJSON(json: any): Friend {
  return FriendFromJSONTyped(json, false);
}

export function FriendFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Friend {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    senderId: json["sender_id"],
    receiverId: json["receiver_id"],
    status: json["status"],
    createdAt: new Date(json["created_at"]),
    sender: UserFromJSON(json["sender"]),
    receiver: UserFromJSON(json["receiver"]),
  };
}

export function FriendToJSON(json: any): Friend {
  return FriendToJSONTyped(json, false);
}

export function FriendToJSONTyped(
  value?: Friend | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    sender_id: value["senderId"],
    receiver_id: value["receiverId"],
    status: value["status"],
    created_at: value["createdAt"].toISOString(),
    sender: UserToJSON(value["sender"]),
    receiver: UserToJSON(value["receiver"]),
  };
}
