/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Game
 */
export interface Game {
  /**
   *
   * @type {number}
   * @memberof Game
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Game
   */
  roomIdentifier: string;
  /**
   *
   * @type {string}
   * @memberof Game
   */
  status: GameStatusEnum;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  player1UserId: number;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  player2UserId: number;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  winnerUserId: number;
  /**
   *
   * @type {Array<number>}
   * @memberof Game
   */
  score: Array<number>;
  /**
   *
   * @type {Date}
   * @memberof Game
   */
  endedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Game
   */
  createdAt: Date;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  inviteId: number;
}

/**
 * @export
 */
export const GameStatusEnum = {
  Pending: "pending",
  Countdown: "countdown",
  Ongoing: "ongoing",
  Closed: "closed",
  Cancelled: "cancelled",
} as const;
export type GameStatusEnum =
  (typeof GameStatusEnum)[keyof typeof GameStatusEnum];

/**
 * Check if a given object implements the Game interface.
 */
export function instanceOfGame(value: object): value is Game {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("roomIdentifier" in value) || value["roomIdentifier"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("player1UserId" in value) || value["player1UserId"] === undefined)
    return false;
  if (!("player2UserId" in value) || value["player2UserId"] === undefined)
    return false;
  if (!("winnerUserId" in value) || value["winnerUserId"] === undefined)
    return false;
  if (!("score" in value) || value["score"] === undefined) return false;
  if (!("endedAt" in value) || value["endedAt"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("inviteId" in value) || value["inviteId"] === undefined) return false;
  return true;
}

export function GameFromJSON(json: any): Game {
  return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Game {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    roomIdentifier: json["room_identifier"],
    status: json["status"],
    player1UserId: json["player1_user_id"],
    player2UserId: json["player2_user_id"],
    winnerUserId: json["winner_user_id"],
    score: json["score"],
    endedAt: new Date(json["ended_at"]),
    createdAt: new Date(json["created_at"]),
    inviteId: json["invite_id"],
  };
}

export function GameToJSON(json: any): Game {
  return GameToJSONTyped(json, false);
}

export function GameToJSONTyped(
  value?: Game | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    room_identifier: value["roomIdentifier"],
    status: value["status"],
    player1_user_id: value["player1UserId"],
    player2_user_id: value["player2UserId"],
    winner_user_id: value["winnerUserId"],
    score: value["score"],
    ended_at: value["endedAt"].toISOString(),
    created_at: value["createdAt"].toISOString(),
    invite_id: value["inviteId"],
  };
}
