/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    gameId: number;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    player1UserId: number;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    player2UserId: number;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    winnerUserId: number;
    /**
     * 
     * @type {User}
     * @memberof Game
     */
    player1User: User;
    /**
     * 
     * @type {User}
     * @memberof Game
     */
    player2User: User;
    /**
     * 
     * @type {User}
     * @memberof Game
     */
    winner: User;
    /**
     * 
     * @type {boolean}
     * @memberof Game
     */
    isLadderGame: boolean;
}

/**
 * Check if a given object implements the Game interface.
 */
export function instanceOfGame(value: object): value is Game {
    if (!('gameId' in value) || value['gameId'] === undefined) return false;
    if (!('player1UserId' in value) || value['player1UserId'] === undefined) return false;
    if (!('player2UserId' in value) || value['player2UserId'] === undefined) return false;
    if (!('winnerUserId' in value) || value['winnerUserId'] === undefined) return false;
    if (!('player1User' in value) || value['player1User'] === undefined) return false;
    if (!('player2User' in value) || value['player2User'] === undefined) return false;
    if (!('winner' in value) || value['winner'] === undefined) return false;
    if (!('isLadderGame' in value) || value['isLadderGame'] === undefined) return false;
    return true;
}

export function GameFromJSON(json: any): Game {
    return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Game {
    if (json == null) {
        return json;
    }
    return {
        
        'gameId': json['gameId'],
        'player1UserId': json['player1_user_id'],
        'player2UserId': json['player2_user_id'],
        'winnerUserId': json['winner_user_id'],
        'player1User': UserFromJSON(json['player1User']),
        'player2User': UserFromJSON(json['player2User']),
        'winner': UserFromJSON(json['winner']),
        'isLadderGame': json['is_ladder_game'],
    };
}

export function GameToJSON(json: any): Game {
    return GameToJSONTyped(json, false);
}

export function GameToJSONTyped(value?: Game | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gameId': value['gameId'],
        'player1_user_id': value['player1UserId'],
        'player2_user_id': value['player2UserId'],
        'winner_user_id': value['winnerUserId'],
        'player1User': UserToJSON(value['player1User']),
        'player2User': UserToJSON(value['player2User']),
        'winner': UserToJSON(value['winner']),
        'is_ladder_game': value['isLadderGame'],
    };
}

