/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Friend } from './Friend';
import {
    FriendFromJSON,
    FriendFromJSONTyped,
    FriendToJSON,
    FriendToJSONTyped,
} from './Friend';

/**
 * 
 * @export
 * @interface GetFriendRequestsDto
 */
export interface GetFriendRequestsDto {
    /**
     * The list of friend requests.
     * @type {Array<Friend>}
     * @memberof GetFriendRequestsDto
     */
    data: Array<Friend>;
    /**
     * The total number of friend requests.
     * @type {number}
     * @memberof GetFriendRequestsDto
     */
    total: number;
    /**
     * The current page number.
     * @type {number}
     * @memberof GetFriendRequestsDto
     */
    page: number;
    /**
     * The number of requests per page.
     * @type {number}
     * @memberof GetFriendRequestsDto
     */
    pageSize: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof GetFriendRequestsDto
     */
    totalPages: number;
}

/**
 * Check if a given object implements the GetFriendRequestsDto interface.
 */
export function instanceOfGetFriendRequestsDto(value: object): value is GetFriendRequestsDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function GetFriendRequestsDtoFromJSON(json: any): GetFriendRequestsDto {
    return GetFriendRequestsDtoFromJSONTyped(json, false);
}

export function GetFriendRequestsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFriendRequestsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(FriendFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
    };
}

export function GetFriendRequestsDtoToJSON(json: any): GetFriendRequestsDto {
    return GetFriendRequestsDtoToJSONTyped(json, false);
}

export function GetFriendRequestsDtoToJSONTyped(value?: GetFriendRequestsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(FriendToJSON)),
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalPages': value['totalPages'],
    };
}

