/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InviteResponseDto
 */
export interface InviteResponseDto {
  /**
   * Whether the operation was successful
   * @type {boolean}
   * @memberof InviteResponseDto
   */
  success: boolean;
  /**
   * Response message
   * @type {string}
   * @memberof InviteResponseDto
   */
  message: string;
}

/**
 * Check if a given object implements the InviteResponseDto interface.
 */
export function instanceOfInviteResponseDto(
  value: object,
): value is InviteResponseDto {
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function InviteResponseDtoFromJSON(json: any): InviteResponseDto {
  return InviteResponseDtoFromJSONTyped(json, false);
}

export function InviteResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InviteResponseDto {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    message: json["message"],
  };
}

export function InviteResponseDtoToJSON(json: any): InviteResponseDto {
  return InviteResponseDtoToJSONTyped(json, false);
}

export function InviteResponseDtoToJSONTyped(
  value?: InviteResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    message: value["message"],
  };
}
