/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Invite
 */
export interface Invite {
  /**
   *
   * @type {number}
   * @memberof Invite
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Invite
   */
  senderUserId: number;
  /**
   *
   * @type {number}
   * @memberof Invite
   */
  receiverUserId: number;
  /**
   *
   * @type {string}
   * @memberof Invite
   */
  status: InviteStatusEnum;
  /**
   *
   * @type {string}
   * @memberof Invite
   */
  gameRoomId: string;
  /**
   *
   * @type {Date}
   * @memberof Invite
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Invite
   */
  expiresAt: Date;
}

/**
 * @export
 */
export const InviteStatusEnum = {
  Pending: "pending",
  Accepted: "accepted",
  Declined: "declined",
  Expired: "expired",
} as const;
export type InviteStatusEnum =
  (typeof InviteStatusEnum)[keyof typeof InviteStatusEnum];

/**
 * Check if a given object implements the Invite interface.
 */
export function instanceOfInvite(value: object): value is Invite {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("senderUserId" in value) || value["senderUserId"] === undefined)
    return false;
  if (!("receiverUserId" in value) || value["receiverUserId"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("gameRoomId" in value) || value["gameRoomId"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("expiresAt" in value) || value["expiresAt"] === undefined) return false;
  return true;
}

export function InviteFromJSON(json: any): Invite {
  return InviteFromJSONTyped(json, false);
}

export function InviteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Invite {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    senderUserId: json["senderUserId"],
    receiverUserId: json["receiverUserId"],
    status: json["status"],
    gameRoomId: json["gameRoomId"],
    createdAt: new Date(json["createdAt"]),
    expiresAt: new Date(json["expiresAt"]),
  };
}

export function InviteToJSON(json: any): Invite {
  return InviteToJSONTyped(json, false);
}

export function InviteToJSONTyped(
  value?: Invite | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    senderUserId: value["senderUserId"],
    receiverUserId: value["receiverUserId"],
    status: value["status"],
    gameRoomId: value["gameRoomId"],
    createdAt: value["createdAt"].toISOString(),
    expiresAt: value["expiresAt"].toISOString(),
  };
}
