/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeResponseSuccess
 */
export interface MeResponseSuccess {
    /**
     * 
     * @type {number}
     * @memberof MeResponseSuccess
     */
    id: number;
    /**
     * The url to avatar
     * @type {string}
     * @memberof MeResponseSuccess
     */
    avatar: string;
    /**
     * The nickname of the user.
     * @type {string}
     * @memberof MeResponseSuccess
     */
    nickname: string;
    /**
     * The email of the user.
     * @type {string}
     * @memberof MeResponseSuccess
     */
    email: string;
    /**
     * The ladder level of the user.
     * @type {number}
     * @memberof MeResponseSuccess
     */
    ladderLevel: number;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof MeResponseSuccess
     */
    enableTwoFactor: boolean;
}

/**
 * Check if a given object implements the MeResponseSuccess interface.
 */
export function instanceOfMeResponseSuccess(value: object): value is MeResponseSuccess {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('ladderLevel' in value) || value['ladderLevel'] === undefined) return false;
    if (!('enableTwoFactor' in value) || value['enableTwoFactor'] === undefined) return false;
    return true;
}

export function MeResponseSuccessFromJSON(json: any): MeResponseSuccess {
    return MeResponseSuccessFromJSONTyped(json, false);
}

export function MeResponseSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponseSuccess {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatar': json['avatar'],
        'nickname': json['nickname'],
        'email': json['email'],
        'ladderLevel': json['ladder_level'],
        'enableTwoFactor': json['enable_two_factor'],
    };
}

export function MeResponseSuccessToJSON(json: any): MeResponseSuccess {
    return MeResponseSuccessToJSONTyped(json, false);
}

export function MeResponseSuccessToJSONTyped(value?: MeResponseSuccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'avatar': value['avatar'],
        'nickname': value['nickname'],
        'email': value['email'],
        'ladder_level': value['ladderLevel'],
        'enable_two_factor': value['enableTwoFactor'],
    };
}

