/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface MessagesResponse
 */
export interface MessagesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof MessagesResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof MessagesResponse
     */
    data?: Array<ChatMessage>;
    /**
     * 
     * @type {string}
     * @memberof MessagesResponse
     */
    message: string;
}

/**
 * Check if a given object implements the MessagesResponse interface.
 */
export function instanceOfMessagesResponse(value: object): value is MessagesResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MessagesResponseFromJSON(json: any): MessagesResponse {
    return MessagesResponseFromJSONTyped(json, false);
}

export function MessagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ChatMessageFromJSON)),
        'message': json['message'],
    };
}

export function MessagesResponseToJSON(json: any): MessagesResponse {
    return MessagesResponseToJSONTyped(json, false);
}

export function MessagesResponseToJSONTyped(value?: MessagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ChatMessageToJSON)),
        'message': value['message'],
    };
}

