/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlayerStatisticsDto
 */
export interface PlayerStatisticsDto {
  /**
   * Total number of games played
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  totalGames: number;
  /**
   * Number of games won
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  gamesWon: number;
  /**
   * Number of games lost
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  gamesLost: number;
  /**
   * Win percentage
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  winPercentage: number;
  /**
   * Total points scored
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  totalPoints: number;
  /**
   * Average points per game
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  averagePointsPerGame: number;
  /**
   * Longest win streak
   * @type {number}
   * @memberof PlayerStatisticsDto
   */
  longestWinStreak: number;
}

/**
 * Check if a given object implements the PlayerStatisticsDto interface.
 */
export function instanceOfPlayerStatisticsDto(
  value: object,
): value is PlayerStatisticsDto {
  if (!("totalGames" in value) || value["totalGames"] === undefined)
    return false;
  if (!("gamesWon" in value) || value["gamesWon"] === undefined) return false;
  if (!("gamesLost" in value) || value["gamesLost"] === undefined) return false;
  if (!("winPercentage" in value) || value["winPercentage"] === undefined)
    return false;
  if (!("totalPoints" in value) || value["totalPoints"] === undefined)
    return false;
  if (
    !("averagePointsPerGame" in value) ||
    value["averagePointsPerGame"] === undefined
  )
    return false;
  if (!("longestWinStreak" in value) || value["longestWinStreak"] === undefined)
    return false;
  return true;
}

export function PlayerStatisticsDtoFromJSON(json: any): PlayerStatisticsDto {
  return PlayerStatisticsDtoFromJSONTyped(json, false);
}

export function PlayerStatisticsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlayerStatisticsDto {
  if (json == null) {
    return json;
  }
  return {
    totalGames: json["totalGames"],
    gamesWon: json["gamesWon"],
    gamesLost: json["gamesLost"],
    winPercentage: json["winPercentage"],
    totalPoints: json["totalPoints"],
    averagePointsPerGame: json["averagePointsPerGame"],
    longestWinStreak: json["longestWinStreak"],
  };
}

export function PlayerStatisticsDtoToJSON(json: any): PlayerStatisticsDto {
  return PlayerStatisticsDtoToJSONTyped(json, false);
}

export function PlayerStatisticsDtoToJSONTyped(
  value?: PlayerStatisticsDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    totalGames: value["totalGames"],
    gamesWon: value["gamesWon"],
    gamesLost: value["gamesLost"],
    winPercentage: value["winPercentage"],
    totalPoints: value["totalPoints"],
    averagePointsPerGame: value["averagePointsPerGame"],
    longestWinStreak: value["longestWinStreak"],
  };
}
