/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueueStatusResponse
 */
export interface QueueStatusResponse {
  /**
   * Game object if match found, empty array otherwise
   * @type {object}
   * @memberof QueueStatusResponse
   */
  game: object | null;
  /**
   * Time spent in queue in seconds
   * @type {number}
   * @memberof QueueStatusResponse
   */
  secondsInQueue: number;
  /**
   * Whether the operation was successful
   * @type {boolean}
   * @memberof QueueStatusResponse
   */
  success: boolean;
  /**
   * Status message
   * @type {string}
   * @memberof QueueStatusResponse
   */
  message: string;
}

/**
 * Check if a given object implements the QueueStatusResponse interface.
 */
export function instanceOfQueueStatusResponse(
  value: object,
): value is QueueStatusResponse {
  if (!("game" in value) || value["game"] === undefined) return false;
  if (!("secondsInQueue" in value) || value["secondsInQueue"] === undefined)
    return false;
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function QueueStatusResponseFromJSON(json: any): QueueStatusResponse {
  return QueueStatusResponseFromJSONTyped(json, false);
}

export function QueueStatusResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueStatusResponse {
  if (json == null) {
    return json;
  }
  return {
    game: json["Game"],
    secondsInQueue: json["SecondsInQueue"],
    success: json["success"],
    message: json["message"],
  };
}

export function QueueStatusResponseToJSON(json: any): QueueStatusResponse {
  return QueueStatusResponseToJSONTyped(json, false);
}

export function QueueStatusResponseToJSONTyped(
  value?: QueueStatusResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    Game: value["game"],
    SecondsInQueue: value["secondsInQueue"],
    success: value["success"],
    message: value["message"],
  };
}
