/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueueUserInQueueResponse
 */
export interface QueueUserInQueueResponse {
  /**
   * If user is in queue or not
   * @type {boolean}
   * @memberof QueueUserInQueueResponse
   */
  isInQueue: boolean;
}

/**
 * Check if a given object implements the QueueUserInQueueResponse interface.
 */
export function instanceOfQueueUserInQueueResponse(
  value: object,
): value is QueueUserInQueueResponse {
  if (!("isInQueue" in value) || value["isInQueue"] === undefined) return false;
  return true;
}

export function QueueUserInQueueResponseFromJSON(
  json: any,
): QueueUserInQueueResponse {
  return QueueUserInQueueResponseFromJSONTyped(json, false);
}

export function QueueUserInQueueResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueUserInQueueResponse {
  if (json == null) {
    return json;
  }
  return {
    isInQueue: json["isInQueue"],
  };
}

export function QueueUserInQueueResponseToJSON(
  json: any,
): QueueUserInQueueResponse {
  return QueueUserInQueueResponseToJSONTyped(json, false);
}

export function QueueUserInQueueResponseToJSONTyped(
  value?: QueueUserInQueueResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    isInQueue: value["isInQueue"],
  };
}
