/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueueJoinResponse
 */
export interface QueueJoinResponse {
  /**
   * Whether the operation was successful
   * @type {boolean}
   * @memberof QueueJoinResponse
   */
  success: boolean;
  /**
   * Status message
   * @type {string}
   * @memberof QueueJoinResponse
   */
  message: string;
}

/**
 * Check if a given object implements the QueueJoinResponse interface.
 */
export function instanceOfQueueJoinResponse(
  value: object,
): value is QueueJoinResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function QueueJoinResponseFromJSON(json: any): QueueJoinResponse {
  return QueueJoinResponseFromJSONTyped(json, false);
}

export function QueueJoinResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueJoinResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    message: json["message"],
  };
}

export function QueueJoinResponseToJSON(json: any): QueueJoinResponse {
  return QueueJoinResponseToJSONTyped(json, false);
}

export function QueueJoinResponseToJSONTyped(
  value?: QueueJoinResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    message: value["message"],
  };
}
