/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SearchUserResponseDto
 */
export interface SearchUserResponseDto {
  /**
   * ID of the user
   * @type {number}
   * @memberof SearchUserResponseDto
   */
  id: number;
  /**
   * Nickname of the user
   * @type {string}
   * @memberof SearchUserResponseDto
   */
  nickname: string;
  /**
   * Email of the user
   * @type {string}
   * @memberof SearchUserResponseDto
   */
  email: string;
  /**
   * Avatar URL of the user
   * @type {string}
   * @memberof SearchUserResponseDto
   */
  avatar: string;
}

/**
 * Check if a given object implements the SearchUserResponseDto interface.
 */
export function instanceOfSearchUserResponseDto(
  value: object,
): value is SearchUserResponseDto {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("nickname" in value) || value["nickname"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("avatar" in value) || value["avatar"] === undefined) return false;
  return true;
}

export function SearchUserResponseDtoFromJSON(
  json: any,
): SearchUserResponseDto {
  return SearchUserResponseDtoFromJSONTyped(json, false);
}

export function SearchUserResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchUserResponseDto {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    nickname: json["nickname"],
    email: json["email"],
    avatar: json["avatar"],
  };
}

export function SearchUserResponseDtoToJSON(json: any): SearchUserResponseDto {
  return SearchUserResponseDtoToJSONTyped(json, false);
}

export function SearchUserResponseDtoToJSONTyped(
  value?: SearchUserResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    nickname: value["nickname"],
    email: value["email"],
    avatar: value["avatar"],
  };
}
