/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateAddUserToBlockedListDto
 */
export interface UpdateAddUserToBlockedListDto {
  /**
   * The ID of the user to block.
   * @type {number}
   * @memberof UpdateAddUserToBlockedListDto
   */
  targetUserId: number;
  /**
   * The nickname of the user.
   * @type {string}
   * @memberof UpdateAddUserToBlockedListDto
   */
  nickname?: string;
  /**
   * The avatar of the user.
   * @type {string}
   * @memberof UpdateAddUserToBlockedListDto
   */
  avatar?: string;
  /**
   * The two factor authentication status of the user.
   * @type {boolean}
   * @memberof UpdateAddUserToBlockedListDto
   */
  twoFactorEnabled?: boolean;
}

/**
 * Check if a given object implements the UpdateAddUserToBlockedListDto interface.
 */
export function instanceOfUpdateAddUserToBlockedListDto(
  value: object,
): value is UpdateAddUserToBlockedListDto {
  if (!("targetUserId" in value) || value["targetUserId"] === undefined)
    return false;
  return true;
}

export function UpdateAddUserToBlockedListDtoFromJSON(
  json: any,
): UpdateAddUserToBlockedListDto {
  return UpdateAddUserToBlockedListDtoFromJSONTyped(json, false);
}

export function UpdateAddUserToBlockedListDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateAddUserToBlockedListDto {
  if (json == null) {
    return json;
  }
  return {
    targetUserId: json["targetUserId"],
    nickname: json["nickname"] == null ? undefined : json["nickname"],
    avatar: json["avatar"] == null ? undefined : json["avatar"],
    twoFactorEnabled:
      json["two_factor_enabled"] == null
        ? undefined
        : json["two_factor_enabled"],
  };
}

export function UpdateAddUserToBlockedListDtoToJSON(
  json: any,
): UpdateAddUserToBlockedListDto {
  return UpdateAddUserToBlockedListDtoToJSONTyped(json, false);
}

export function UpdateAddUserToBlockedListDtoToJSONTyped(
  value?: UpdateAddUserToBlockedListDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    targetUserId: value["targetUserId"],
    nickname: value["nickname"],
    avatar: value["avatar"],
    two_factor_enabled: value["twoFactorEnabled"],
  };
}
