/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateUserResponse
 */
export interface UpdateUserResponse {
  /**
   *
   * @type {boolean}
   * @memberof UpdateUserResponse
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof UpdateUserResponse
   */
  message?: string;
  /**
   *
   * @type {object}
   * @memberof UpdateUserResponse
   */
  errors?: object;
}

/**
 * Check if a given object implements the UpdateUserResponse interface.
 */
export function instanceOfUpdateUserResponse(
  value: object,
): value is UpdateUserResponse {
  if (!("success" in value) || value["success"] === undefined) return false;
  return true;
}

export function UpdateUserResponseFromJSON(json: any): UpdateUserResponse {
  return UpdateUserResponseFromJSONTyped(json, false);
}

export function UpdateUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserResponse {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    message: json["message"] == null ? undefined : json["message"],
    errors: json["errors"] == null ? undefined : json["errors"],
  };
}

export function UpdateUserResponseToJSON(json: any): UpdateUserResponse {
  return UpdateUserResponseToJSONTyped(json, false);
}

export function UpdateUserResponseToJSONTyped(
  value?: UpdateUserResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    message: value["message"],
    errors: value["errors"],
  };
}
