/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateChatParticipantDto
 */
export interface UpdateChatParticipantDto {
  /**
   * Chat participant role
   * @type {string}
   * @memberof UpdateChatParticipantDto
   */
  chatParticipantRole?: UpdateChatParticipantDtoChatParticipantRoleEnum;
  /**
   * Is banned
   * @type {boolean}
   * @memberof UpdateChatParticipantDto
   */
  isBanned?: boolean;
  /**
   * Is muted
   * @type {boolean}
   * @memberof UpdateChatParticipantDto
   */
  isMuted?: boolean;
  /**
   * left at this date
   * @type {Date}
   * @memberof UpdateChatParticipantDto
   */
  leftAt?: Date;
  /**
   * Banned until date
   * @type {Date}
   * @memberof UpdateChatParticipantDto
   */
  bannedUntil?: Date;
}

/**
 * @export
 */
export const UpdateChatParticipantDtoChatParticipantRoleEnum = {
  Owner: "owner",
  Admin: "admin",
  Guest: "guest",
} as const;
export type UpdateChatParticipantDtoChatParticipantRoleEnum =
  (typeof UpdateChatParticipantDtoChatParticipantRoleEnum)[keyof typeof UpdateChatParticipantDtoChatParticipantRoleEnum];

/**
 * Check if a given object implements the UpdateChatParticipantDto interface.
 */
export function instanceOfUpdateChatParticipantDto(
  value: object,
): value is UpdateChatParticipantDto {
  return true;
}

export function UpdateChatParticipantDtoFromJSON(
  json: any,
): UpdateChatParticipantDto {
  return UpdateChatParticipantDtoFromJSONTyped(json, false);
}

export function UpdateChatParticipantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateChatParticipantDto {
  if (json == null) {
    return json;
  }
  return {
    chatParticipantRole:
      json["chat_participant_role"] == null
        ? undefined
        : json["chat_participant_role"],
    isBanned: json["is_banned"] == null ? undefined : json["is_banned"],
    isMuted: json["is_muted"] == null ? undefined : json["is_muted"],
    leftAt: json["leftAt"] == null ? undefined : new Date(json["leftAt"]),
    bannedUntil:
      json["banned_until"] == null ? undefined : new Date(json["banned_until"]),
  };
}

export function UpdateChatParticipantDtoToJSON(
  json: any,
): UpdateChatParticipantDto {
  return UpdateChatParticipantDtoToJSONTyped(json, false);
}

export function UpdateChatParticipantDtoToJSONTyped(
  value?: UpdateChatParticipantDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chat_participant_role: value["chatParticipantRole"],
    is_banned: value["isBanned"],
    is_muted: value["isMuted"],
    leftAt: value["leftAt"] == null ? undefined : value["leftAt"].toISOString(),
    banned_until:
      value["bannedUntil"] == null
        ? undefined
        : value["bannedUntil"].toISOString(),
  };
}
