/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";
import type { Blocked } from "./Blocked";
import {
  BlockedFromJSON,
  BlockedFromJSONTyped,
  BlockedToJSON,
  BlockedToJSONTyped,
} from "./Blocked";

/**
 *
 * @export
 * @interface UpdateAddUserToBlockedListDto
 */
export interface UpdateAddUserToBlockedListDto {
  /**
   * The ID of the user to block.
   * @type {Array<Blocked>}
   * @memberof UpdateAddUserToBlockedListDto
   */
  blockedUsers: Array<Blocked>;
  /**
   * The ID of the user to block.
   * @type {User}
   * @memberof UpdateAddUserToBlockedListDto
   */
  targerUser: User;
  /**
   * The nickname of the user.
   * @type {string}
   * @memberof UpdateAddUserToBlockedListDto
   */
  nickname?: string;
  /**
   * The avatar of the user.
   * @type {string}
   * @memberof UpdateAddUserToBlockedListDto
   */
  avatar?: string;
  /**
   * The two factor authentication status of the user.
   * @type {boolean}
   * @memberof UpdateAddUserToBlockedListDto
   */
  twoFactorEnabled?: boolean;
}

/**
 * Check if a given object implements the UpdateAddUserToBlockedListDto interface.
 */
export function instanceOfUpdateAddUserToBlockedListDto(
  value: object,
): value is UpdateAddUserToBlockedListDto {
  if (!("blockedUsers" in value) || value["blockedUsers"] === undefined)
    return false;
  if (!("targerUser" in value) || value["targerUser"] === undefined)
    return false;
  return true;
}

export function UpdateAddUserToBlockedListDtoFromJSON(
  json: any,
): UpdateAddUserToBlockedListDto {
  return UpdateAddUserToBlockedListDtoFromJSONTyped(json, false);
}

export function UpdateAddUserToBlockedListDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateAddUserToBlockedListDto {
  if (json == null) {
    return json;
  }
  return {
    blockedUsers: (json["blockedUsers"] as Array<any>).map(BlockedFromJSON),
    targerUser: UserFromJSON(json["targerUser"]),
    nickname: json["nickname"] == null ? undefined : json["nickname"],
    avatar: json["avatar"] == null ? undefined : json["avatar"],
    twoFactorEnabled:
      json["two_factor_enabled"] == null
        ? undefined
        : json["two_factor_enabled"],
  };
}

export function UpdateAddUserToBlockedListDtoToJSON(
  json: any,
): UpdateAddUserToBlockedListDto {
  return UpdateAddUserToBlockedListDtoToJSONTyped(json, false);
}

export function UpdateAddUserToBlockedListDtoToJSONTyped(
  value?: UpdateAddUserToBlockedListDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    blockedUsers: (value["blockedUsers"] as Array<any>).map(BlockedToJSON),
    targerUser: UserToJSON(value["targerUser"]),
    nickname: value["nickname"],
    avatar: value["avatar"],
    two_factor_enabled: value["twoFactorEnabled"],
  };
}
