/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateChatRoomDto
 */
export interface UpdateChatRoomDto {
  /**
   *
   * @type {string}
   * @memberof UpdateChatRoomDto
   */
  password?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateChatRoomDto
   */
  chatRoomType?: UpdateChatRoomDtoChatRoomTypeEnum;
}

/**
 * @export
 */
export const UpdateChatRoomDtoChatRoomTypeEnum = {
  Public: "public",
  Protected: "protected",
  Private: "private",
  Dm: "Dm",
} as const;
export type UpdateChatRoomDtoChatRoomTypeEnum =
  (typeof UpdateChatRoomDtoChatRoomTypeEnum)[keyof typeof UpdateChatRoomDtoChatRoomTypeEnum];

/**
 * Check if a given object implements the UpdateChatRoomDto interface.
 */
export function instanceOfUpdateChatRoomDto(
  value: object,
): value is UpdateChatRoomDto {
  return true;
}

export function UpdateChatRoomDtoFromJSON(json: any): UpdateChatRoomDto {
  return UpdateChatRoomDtoFromJSONTyped(json, false);
}

export function UpdateChatRoomDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateChatRoomDto {
  if (json == null) {
    return json;
  }
  return {
    password: json["password"] == null ? undefined : json["password"],
    chatRoomType:
      json["chat_room_type"] == null ? undefined : json["chat_room_type"],
  };
}

export function UpdateChatRoomDtoToJSON(json: any): UpdateChatRoomDto {
  return UpdateChatRoomDtoToJSONTyped(json, false);
}

export function UpdateChatRoomDtoToJSONTyped(
  value?: UpdateChatRoomDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    password: value["password"],
    chat_room_type: value["chatRoomType"],
  };
}
