/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Game } from './Game';
import {
    GameFromJSON,
    GameFromJSONTyped,
    GameToJSON,
    GameToJSONTyped,
} from './Game';
import type { Friend } from './Friend';
import {
    FriendFromJSON,
    FriendFromJSONTyped,
    FriendToJSON,
    FriendToJSONTyped,
} from './Friend';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';
import type { ChatParticipant } from './ChatParticipant';
import {
    ChatParticipantFromJSON,
    ChatParticipantFromJSONTyped,
    ChatParticipantToJSON,
    ChatParticipantToJSONTyped,
} from './ChatParticipant';
import type { Achievement } from './Achievement';
import {
    AchievementFromJSON,
    AchievementFromJSONTyped,
    AchievementToJSON,
    AchievementToJSONTyped,
} from './Achievement';
import type { Blocked } from './Blocked';
import {
    BlockedFromJSON,
    BlockedFromJSONTyped,
    BlockedToJSON,
    BlockedToJSONTyped,
} from './Blocked';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The ID of the user.
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * The url to avatar
     * @type {string}
     * @memberof User
     */
    avatar: string;
    /**
     * The nickname of the user.
     * @type {string}
     * @memberof User
     */
    nickname: string;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof User
     */
    enableTwoFactor: boolean;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof User
     */
    isSecondAuthDone: boolean;
    /**
     * The two factor authentication status of the user.
     * @type {number}
     * @memberof User
     */
    secondAuthCode: number;
    /**
     * The email of the user.
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * The ladder level of the user.
     * @type {number}
     * @memberof User
     */
    ladderLevel: number;
    /**
     * The status of the user.
     * @type {string}
     * @memberof User
     */
    userStatus: UserUserStatusEnum;
    /**
     * 
     * @type {Array<Achievement>}
     * @memberof User
     */
    achievements: Array<Achievement>;
    /**
     * 
     * @type {Array<Blocked>}
     * @memberof User
     */
    blockedUsers: Array<Blocked>;
    /**
     * 
     * @type {Array<Blocked>}
     * @memberof User
     */
    users: Array<Blocked>;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof User
     */
    chatMessages: Array<ChatMessage>;
    /**
     * 
     * @type {Array<ChatParticipant>}
     * @memberof User
     */
    chatParticipants: Array<ChatParticipant>;
    /**
     * 
     * @type {Array<Friend>}
     * @memberof User
     */
    friends1: Array<Friend>;
    /**
     * 
     * @type {Array<Friend>}
     * @memberof User
     */
    friends2: Array<Friend>;
    /**
     * 
     * @type {Array<Game>}
     * @memberof User
     */
    players1: Array<Game>;
    /**
     * 
     * @type {Array<Game>}
     * @memberof User
     */
    players2: Array<Game>;
    /**
     * 
     * @type {Array<Game>}
     * @memberof User
     */
    winners: Array<Game>;
}


/**
 * @export
 */
export const UserUserStatusEnum = {
    Offline: 'offline',
    Online: 'online',
    Waiting: 'waiting',
    Playing: 'playing'
} as const;
export type UserUserStatusEnum = typeof UserUserStatusEnum[keyof typeof UserUserStatusEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('enableTwoFactor' in value) || value['enableTwoFactor'] === undefined) return false;
    if (!('isSecondAuthDone' in value) || value['isSecondAuthDone'] === undefined) return false;
    if (!('secondAuthCode' in value) || value['secondAuthCode'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('ladderLevel' in value) || value['ladderLevel'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    if (!('achievements' in value) || value['achievements'] === undefined) return false;
    if (!('blockedUsers' in value) || value['blockedUsers'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('chatMessages' in value) || value['chatMessages'] === undefined) return false;
    if (!('chatParticipants' in value) || value['chatParticipants'] === undefined) return false;
    if (!('friends1' in value) || value['friends1'] === undefined) return false;
    if (!('friends2' in value) || value['friends2'] === undefined) return false;
    if (!('players1' in value) || value['players1'] === undefined) return false;
    if (!('players2' in value) || value['players2'] === undefined) return false;
    if (!('winners' in value) || value['winners'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatar': json['avatar'],
        'nickname': json['nickname'],
        'enableTwoFactor': json['enable_two_factor'],
        'isSecondAuthDone': json['is_second_auth_done'],
        'secondAuthCode': json['second_auth_code'],
        'email': json['email'],
        'ladderLevel': json['ladder_level'],
        'userStatus': json['user_status'],
        'achievements': ((json['achievements'] as Array<any>).map(AchievementFromJSON)),
        'blockedUsers': ((json['blockedUsers'] as Array<any>).map(BlockedFromJSON)),
        'users': ((json['users'] as Array<any>).map(BlockedFromJSON)),
        'chatMessages': ((json['chatMessages'] as Array<any>).map(ChatMessageFromJSON)),
        'chatParticipants': ((json['chatParticipants'] as Array<any>).map(ChatParticipantFromJSON)),
        'friends1': ((json['friends1'] as Array<any>).map(FriendFromJSON)),
        'friends2': ((json['friends2'] as Array<any>).map(FriendFromJSON)),
        'players1': ((json['players1'] as Array<any>).map(GameFromJSON)),
        'players2': ((json['players2'] as Array<any>).map(GameFromJSON)),
        'winners': ((json['winners'] as Array<any>).map(GameFromJSON)),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'avatar': value['avatar'],
        'nickname': value['nickname'],
        'enable_two_factor': value['enableTwoFactor'],
        'is_second_auth_done': value['isSecondAuthDone'],
        'second_auth_code': value['secondAuthCode'],
        'email': value['email'],
        'ladder_level': value['ladderLevel'],
        'user_status': value['userStatus'],
        'achievements': ((value['achievements'] as Array<any>).map(AchievementToJSON)),
        'blockedUsers': ((value['blockedUsers'] as Array<any>).map(BlockedToJSON)),
        'users': ((value['users'] as Array<any>).map(BlockedToJSON)),
        'chatMessages': ((value['chatMessages'] as Array<any>).map(ChatMessageToJSON)),
        'chatParticipants': ((value['chatParticipants'] as Array<any>).map(ChatParticipantToJSON)),
        'friends1': ((value['friends1'] as Array<any>).map(FriendToJSON)),
        'friends2': ((value['friends2'] as Array<any>).map(FriendToJSON)),
        'players1': ((value['players1'] as Array<any>).map(GameToJSON)),
        'players2': ((value['players2'] as Array<any>).map(GameToJSON)),
        'winners': ((value['winners'] as Array<any>).map(GameToJSON)),
    };
}

