/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The ID of the user.
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * The url to avatar
     * @type {string}
     * @memberof User
     */
    avatar: string;
    /**
     * The nickname of the user.
     * @type {string}
     * @memberof User
     */
    nickname: string;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof User
     */
    twoFactorEnabled: boolean;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof User
     */
    isSecondAuthDone: boolean;
    /**
     * The two factor authentication secret of the user.
     * @type {string}
     * @memberof User
     */
    twoFactorAuthSecret: string;
    /**
     * The email of the user.
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * The ladder level of the user.
     * @type {number}
     * @memberof User
     */
    ladderLevel: number;
    /**
     * The status of the user.
     * @type {string}
     * @memberof User
     */
    userStatus: UserUserStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    achievements: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    blockedUsers: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    users: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    chatMessages: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    chatParticipants: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    sentFriendRequests: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    receivedFriendRequests: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    players1: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    players2: object;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    winners: object;
}


/**
 * @export
 */
export const UserUserStatusEnum = {
    Offline: 'offline',
    Online: 'online',
    Waiting: 'waiting',
    Playing: 'playing'
} as const;
export type UserUserStatusEnum = typeof UserUserStatusEnum[keyof typeof UserUserStatusEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('twoFactorEnabled' in value) || value['twoFactorEnabled'] === undefined) return false;
    if (!('isSecondAuthDone' in value) || value['isSecondAuthDone'] === undefined) return false;
    if (!('twoFactorAuthSecret' in value) || value['twoFactorAuthSecret'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('ladderLevel' in value) || value['ladderLevel'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    if (!('achievements' in value) || value['achievements'] === undefined) return false;
    if (!('blockedUsers' in value) || value['blockedUsers'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('chatMessages' in value) || value['chatMessages'] === undefined) return false;
    if (!('chatParticipants' in value) || value['chatParticipants'] === undefined) return false;
    if (!('sentFriendRequests' in value) || value['sentFriendRequests'] === undefined) return false;
    if (!('receivedFriendRequests' in value) || value['receivedFriendRequests'] === undefined) return false;
    if (!('players1' in value) || value['players1'] === undefined) return false;
    if (!('players2' in value) || value['players2'] === undefined) return false;
    if (!('winners' in value) || value['winners'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatar': json['avatar'],
        'nickname': json['nickname'],
        'twoFactorEnabled': json['two_factor_enabled'],
        'isSecondAuthDone': json['is_second_auth_done'],
        'twoFactorAuthSecret': json['two_factor_auth_secret'],
        'email': json['email'],
        'ladderLevel': json['ladder_level'],
        'userStatus': json['user_status'],
        'achievements': json['achievements'],
        'blockedUsers': json['blockedUsers'],
        'users': json['users'],
        'chatMessages': json['chatMessages'],
        'chatParticipants': json['chatParticipants'],
        'sentFriendRequests': json['sentFriendRequests'],
        'receivedFriendRequests': json['receivedFriendRequests'],
        'players1': json['players1'],
        'players2': json['players2'],
        'winners': json['winners'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'avatar': value['avatar'],
        'nickname': value['nickname'],
        'two_factor_enabled': value['twoFactorEnabled'],
        'is_second_auth_done': value['isSecondAuthDone'],
        'two_factor_auth_secret': value['twoFactorAuthSecret'],
        'email': value['email'],
        'ladder_level': value['ladderLevel'],
        'user_status': value['userStatus'],
        'achievements': value['achievements'],
        'blockedUsers': value['blockedUsers'],
        'users': value['users'],
        'chatMessages': value['chatMessages'],
        'chatParticipants': value['chatParticipants'],
        'sentFriendRequests': value['sentFriendRequests'],
        'receivedFriendRequests': value['receivedFriendRequests'],
        'players1': value['players1'],
        'players2': value['players2'],
        'winners': value['winners'],
    };
}

