/* tslint:disable */
/* eslint-disable */
/**
 * Transcendence backend
 * The Transcendence API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Game } from "./Game";
import {
  GameFromJSON,
  GameFromJSONTyped,
  GameToJSON,
  GameToJSONTyped,
} from "./Game";
import type { Friend } from "./Friend";
import {
  FriendFromJSON,
  FriendFromJSONTyped,
  FriendToJSON,
  FriendToJSONTyped,
} from "./Friend";
import type { ChatMessage } from "./ChatMessage";
import {
  ChatMessageFromJSON,
  ChatMessageFromJSONTyped,
  ChatMessageToJSON,
  ChatMessageToJSONTyped,
} from "./ChatMessage";
import type { ChatParticipant } from "./ChatParticipant";
import {
  ChatParticipantFromJSON,
  ChatParticipantFromJSONTyped,
  ChatParticipantToJSON,
  ChatParticipantToJSONTyped,
} from "./ChatParticipant";
import type { Achievement } from "./Achievement";
import {
  AchievementFromJSON,
  AchievementFromJSONTyped,
  AchievementToJSON,
  AchievementToJSONTyped,
} from "./Achievement";
import type { Blocked } from "./Blocked";
import {
  BlockedFromJSON,
  BlockedFromJSONTyped,
  BlockedToJSON,
  BlockedToJSONTyped,
} from "./Blocked";

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * The ID of the user.
   * @type {number}
   * @memberof User
   */
  id: number;
  /**
   * The url to avatar
   * @type {string}
   * @memberof User
   */
  avatar: string;
  /**
   * The nickname of the user.
   * @type {string}
   * @memberof User
   */
  nickname: string;
  /**
   * The two factor authentication status of the user.
   * @type {boolean}
   * @memberof User
   */
  twoFactorEnabled: boolean;
  /**
   * The two factor authentication status of the user.
   * @type {boolean}
   * @memberof User
   */
  isSecondAuthDone: boolean;
  /**
   * The two factor authentication secret of the user.
   * @type {string}
   * @memberof User
   */
  twoFactorAuthSecret: string;
  /**
   * The email of the user.
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   * The ladder level of the user.
   * @type {number}
   * @memberof User
   */
  ladderLevel: number;
  /**
   * The status of the user.
   * @type {string}
   * @memberof User
   */
  userStatus: UserUserStatusEnum;
  /**
   *
   * @type {Array<Achievement>}
   * @memberof User
   */
  achievements?: Array<Achievement>;
  /**
   *
   * @type {Array<Blocked>}
   * @memberof User
   */
  blockedUsers?: Array<Blocked>;
  /**
   *
   * @type {Array<Blocked>}
   * @memberof User
   */
  users?: Array<Blocked>;
  /**
   *
   * @type {Array<ChatMessage>}
   * @memberof User
   */
  chatMessages?: Array<ChatMessage>;
  /**
   *
   * @type {Array<ChatParticipant>}
   * @memberof User
   */
  chatParticipants?: Array<ChatParticipant>;
  /**
   *
   * @type {Array<Friend>}
   * @memberof User
   */
  sentFriendRequests?: Array<Friend>;
  /**
   *
   * @type {Array<Friend>}
   * @memberof User
   */
  receivedFriendRequests?: Array<Friend>;
  /**
   *
   * @type {Array<Game>}
   * @memberof User
   */
  gamesAsPlayer1?: Array<Game>;
  /**
   *
   * @type {Array<Game>}
   * @memberof User
   */
  gamesAsPlayer2?: Array<Game>;
  /**
   *
   * @type {Array<Game>}
   * @memberof User
   */
  gamesWon?: Array<Game>;
}

/**
 * @export
 */
export const UserUserStatusEnum = {
  Offline: "offline",
  Online: "online",
  Waiting: "waiting",
  Playing: "playing",
} as const;
export type UserUserStatusEnum =
  (typeof UserUserStatusEnum)[keyof typeof UserUserStatusEnum];

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("avatar" in value) || value["avatar"] === undefined) return false;
  if (!("nickname" in value) || value["nickname"] === undefined) return false;
  if (!("twoFactorEnabled" in value) || value["twoFactorEnabled"] === undefined)
    return false;
  if (!("isSecondAuthDone" in value) || value["isSecondAuthDone"] === undefined)
    return false;
  if (
    !("twoFactorAuthSecret" in value) ||
    value["twoFactorAuthSecret"] === undefined
  )
    return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("ladderLevel" in value) || value["ladderLevel"] === undefined)
    return false;
  if (!("userStatus" in value) || value["userStatus"] === undefined)
    return false;
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): User {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    avatar: json["avatar"],
    nickname: json["nickname"],
    twoFactorEnabled: json["two_factor_enabled"],
    isSecondAuthDone: json["is_second_auth_done"],
    twoFactorAuthSecret: json["two_factor_auth_secret"],
    email: json["email"],
    ladderLevel: json["ladder_level"],
    userStatus: json["user_status"],
    achievements:
      json["achievements"] == null
        ? undefined
        : (json["achievements"] as Array<any>).map(AchievementFromJSON),
    blockedUsers:
      json["blockedUsers"] == null
        ? undefined
        : (json["blockedUsers"] as Array<any>).map(BlockedFromJSON),
    users:
      json["users"] == null
        ? undefined
        : (json["users"] as Array<any>).map(BlockedFromJSON),
    chatMessages:
      json["chatMessages"] == null
        ? undefined
        : (json["chatMessages"] as Array<any>).map(ChatMessageFromJSON),
    chatParticipants:
      json["chatParticipants"] == null
        ? undefined
        : (json["chatParticipants"] as Array<any>).map(ChatParticipantFromJSON),
    sentFriendRequests:
      json["sentFriendRequests"] == null
        ? undefined
        : (json["sentFriendRequests"] as Array<any>).map(FriendFromJSON),
    receivedFriendRequests:
      json["receivedFriendRequests"] == null
        ? undefined
        : (json["receivedFriendRequests"] as Array<any>).map(FriendFromJSON),
    gamesAsPlayer1:
      json["gamesAsPlayer1"] == null
        ? undefined
        : (json["gamesAsPlayer1"] as Array<any>).map(GameFromJSON),
    gamesAsPlayer2:
      json["gamesAsPlayer2"] == null
        ? undefined
        : (json["gamesAsPlayer2"] as Array<any>).map(GameFromJSON),
    gamesWon:
      json["gamesWon"] == null
        ? undefined
        : (json["gamesWon"] as Array<any>).map(GameFromJSON),
  };
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(
  value?: User | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    avatar: value["avatar"],
    nickname: value["nickname"],
    two_factor_enabled: value["twoFactorEnabled"],
    is_second_auth_done: value["isSecondAuthDone"],
    two_factor_auth_secret: value["twoFactorAuthSecret"],
    email: value["email"],
    ladder_level: value["ladderLevel"],
    user_status: value["userStatus"],
    achievements:
      value["achievements"] == null
        ? undefined
        : (value["achievements"] as Array<any>).map(AchievementToJSON),
    blockedUsers:
      value["blockedUsers"] == null
        ? undefined
        : (value["blockedUsers"] as Array<any>).map(BlockedToJSON),
    users:
      value["users"] == null
        ? undefined
        : (value["users"] as Array<any>).map(BlockedToJSON),
    chatMessages:
      value["chatMessages"] == null
        ? undefined
        : (value["chatMessages"] as Array<any>).map(ChatMessageToJSON),
    chatParticipants:
      value["chatParticipants"] == null
        ? undefined
        : (value["chatParticipants"] as Array<any>).map(ChatParticipantToJSON),
    sentFriendRequests:
      value["sentFriendRequests"] == null
        ? undefined
        : (value["sentFriendRequests"] as Array<any>).map(FriendToJSON),
    receivedFriendRequests:
      value["receivedFriendRequests"] == null
        ? undefined
        : (value["receivedFriendRequests"] as Array<any>).map(FriendToJSON),
    gamesAsPlayer1:
      value["gamesAsPlayer1"] == null
        ? undefined
        : (value["gamesAsPlayer1"] as Array<any>).map(GameToJSON),
    gamesAsPlayer2:
      value["gamesAsPlayer2"] == null
        ? undefined
        : (value["gamesAsPlayer2"] as Array<any>).map(GameToJSON),
    gamesWon:
      value["gamesWon"] == null
        ? undefined
        : (value["gamesWon"] as Array<any>).map(GameToJSON),
  };
}
